name: Deploy kpi-sales on push to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ CI запущен
        run: echo "🚀 GitHub Actions запущен"

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "🧩 Подключение к серверу"
            cd /var/www/html/next/kpi-sales
            git pull origin main
            tmux kill-session -t deploy-session || true
            tmux new -d -s deploy-session "docker-compose up -d --build && echo ✅ Готово"

            echo "⏳ Жду, пока контейнер april-kpi-sales поднимется..."
            for i in {1..90}; do
              if docker ps --filter "name=april-kpi-sales" --filter "status=running" | grep april-kpi-sales; then
                echo "✅ Контейнер запущен!"
                break
              fi
              echo "⌛ Ожидание запуска контейнера..."
              sleep 5
            done


            docker ps -a
            docker logs april-kpi-sales || true
