version: '3.8'

services:
 

  front-konstructor-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP: konstructor 
    container_name: front-konstructor-dev
    # ports:
    #   - "${PORT_KONSTRUCTOR}:5000" 
    ports:
      - "5000:3000"          # API доступен снаружи
    environment:
      - IN_BITRIX=true
      - LOG_FILE_PATH=/app/logs/server.log
      - PORT=3000
      - PDF_PREVIEW_URL=/offer/preview?readonly=true
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - front
    depends_on:
      - redis

  # redis
  redis:
    image: redis:7
    container_name: front-redis
    ports:
      - "6379:6379"
    networks:
      - front

  # nginx:
  #   image: nginx:alpine
  #   container_name: next-kpi-sales-nginx
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - app
  #   networks:
  #     - front

networks:
  front:
