version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next-kpi-sales
    ports:
      - "3000:3000"
    networks:
      - next-kpi-sales-next-net

  nginx:
    image: nginx:alpine
    container_name: next-kpi-sales-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - next-kpi-sales-next-net

networks:
  next-kpi-sales-next-net:
