import {
    createEnumObject,
    createFieldItemsEnum,
    FieldItemCode,
    FieldItemCodesMap,
    FieldWithItems,
} from '../../pbx-field-type.util';
export const PBX_SALES_EVENT_FIELDS = [
    {
        name: 'ОП Название ХО',
        appType: 'xo',
        type: 'string',
        items: [],
        code: 'xo_name',
        lead: 'XO_NAME',
        company: 'XO_NAME',
        deal: 'XO_NAME',
        smart: '',
        task: '',
        app: 'calling',
        order: 210,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП Дата Холодного обзвона',
        appType: 'xo',
        type: 'datetime',
        items: [],
        code: 'xo_date',
        lead: 'XO_DATE',
        company: 'XO_DATE',
        deal: 'XO_DATE',
        smart: '',
        task: '',
        app: 'calling',
        order: 210,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП Ответственный ХО',
        appType: 'xo',
        type: 'employee',
        items: [],
        code: 'xo_responsible',
        lead: 'XO_RESPONSIBLE',
        company: 'XO_RESPONSIBLE',
        deal: 'XO_RESPONSIBLE',
        smart: '',
        task: '',
        app: 'calling',
        order: 210,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП Постановщик ХО',
        appType: 'xo',
        type: 'employee',
        items: [],
        code: 'xo_created',
        lead: 'XO_CREATED',
        company: 'XO_CREATED',
        deal: 'XO_CREATED',
        smart: '',
        task: '',
        app: 'calling',
        order: 210,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП Дата назначенной презентации',
        appType: 'pres',
        type: 'datetime',
        items: [],
        code: 'next_pres_plan_date',
        lead: 'NEXT_PRES_PLAN_DATE',
        company: 'NEXT_PRES_PLAN_DATE',
        deal: 'NEXT_PRES_PLAN_DATE',
        smart: '',
        task: '',
        app: 'calling',
        order: 220,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП Дата последней назначенной презентации',
        appType: 'pres',
        type: 'datetime',
        items: [],
        code: 'last_pres_plan_date',
        lead: 'LAST_PRES_PLAN_DATE',
        company: 'LAST_PRES_PLAN_DATE',
        deal: 'LAST_PRES_PLAN_DATE',
        smart: '',
        task: '',
        app: 'calling',
        order: 220,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП Дата последней проведенной презентации',
        appType: 'pres',
        type: 'datetime',
        items: [],
        code: 'last_pres_done_date',
        lead: 'LAST_PRES_DONE_DATE',
        company: 'LAST_PRES_DONE_DATE',
        deal: 'LAST_PRES_DONE_DATE',
        smart: '',
        task: '',
        app: 'calling',
        order: 220,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП Кто назначил последнюю заявку на презентацию',
        appType: 'pres',
        type: 'employee',
        items: [],
        code: 'last_pres_plan_responsible',
        lead: 'LAST_PRES_PLAN_RESPONSIBLE',
        company: 'LAST_PRES_PLAN_RESPONSIBLE',
        deal: 'LAST_PRES_PLAN_RESPONSIBLE',
        smart: '',
        task: '',
        app: 'calling',
        order: 220,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП Кто провел последнюю презентацию',
        appType: 'pres',
        type: 'employee',
        items: [],
        code: 'last_pres_done_responsible',
        lead: 'LAST_PRES_DONE_RESPONSIBLE',
        company: 'LAST_PRES_DONE_RESPONSIBLE',
        deal: 'LAST_PRES_DONE_RESPONSIBLE',
        smart: '',
        task: '',
        app: 'calling',
        order: 220,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП Проведено презентаций',
        appType: 'pres',
        type: 'integer',
        items: [],
        code: 'pres_count',
        lead: 'PRES_COUNT',
        company: 1709807026,
        deal: 'PRES_COUNT',
        smart: '',
        task: '',
        app: 'calling',
        order: 220,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП Комментарии после презентаций',
        appType: 'pres',
        type: 'multiple',
        items: [],
        code: 'pres_comments',
        lead: 'PRES_COMMENTS',
        company: 'PRES_COMMENTS',
        deal: 'PRES_COMMENTS',
        smart: '',
        task: '',
        app: 'calling',
        order: 220,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: true,
    },
    /*
     * Ответы опросника после презентации (`withCheckPresentation`). Поля
     * заведены на порталах и заполняются ФРЕЙМОМ напрямую в карточке
     * клиента; в реестре они нужны, чтобы бэк умел их читать/писать
     * типизированно (`PBX_SALES_EVENT_FIELD_CODES.op_presentation_xvost`) и
     * чтобы инсталлятор доводил их на новых порталах.
     *
     * `company` пуст намеренно: анкета относится к конкретной презентации,
     * а презентация живёт в лиде и сделке — на компании такое поле хранило
     * бы «последний ответ по любой из сделок» и вводило в заблуждение.
     */
    {
        name: 'ОП Хвост (после презентации)',
        appType: 'pres',
        type: 'string',
        items: [],
        code: 'op_presentation_xvost',
        lead: 'OP_PRESENTATION_XVOST',
        company: '',
        deal: 'OP_PRESENTATION_XVOST',
        smart: '',
        task: '',
        app: 'calling',
        order: 220,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП Пять К (после презентации)',
        appType: 'pres',
        type: 'string',
        items: [],
        code: 'op_presentation_5k',
        lead: 'OP_PRESENTATION_5K',
        company: '',
        deal: 'OP_PRESENTATION_5K',
        smart: '',
        task: '',
        app: 'calling',
        order: 220,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    /*
     * «Пять К» — ПЯТЬ текстовых полей (переделка 01.09.2026).
     *
     * Было девять полей по одному вопросу в каждом; стало пять по теме, а
     * подвопросы живут ВНУТРИ значения текстом (шаблон собирает
     * SURVEY_TEMPLATES в shared/presentation-survey) и в подсказке поля.
     *
     * Коды НОВЫЕ целиком, включая те две темы, что и раньше жили одним
     * полем (конкурент, критерии): решение владельца — «поля новые, запись
     * новая». Переиспользуй мы старый код, ответы на СТАРЫЙ вопрос
     * смешались бы с ответами на новый в одном поле, и разделить их было бы
     * уже нечем.
     *
     * Установлены на лиде и сделке; сводные op_presentation_5k /
     * op_presentation_xvost выше не тронуты.
     */
    {
        name: "5К КЛИЕНТ",
        appType: 'pres',
        type: 'string',
        items: [],
        code: 'op_5k_client',
        lead: 'OP_5K_CLIENT',
        company: '',
        deal: 'OP_5K_CLIENT',
        smart: '',
        task: '',
        app: 'calling',
        order: 220,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: "5К КОМПАНИЯ",
        appType: 'pres',
        type: 'string',
        items: [],
        code: 'op_5k_company',
        lead: 'OP_5K_COMPANY',
        company: '',
        deal: 'OP_5K_COMPANY',
        smart: '',
        task: '',
        app: 'calling',
        order: 220,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: "5К КОЛЛЕГИ",
        appType: 'pres',
        type: 'string',
        items: [],
        code: 'op_5k_colleagues',
        lead: 'OP_5K_COLLEAGUES',
        company: '',
        deal: 'OP_5K_COLLEAGUES',
        smart: '',
        task: '',
        app: 'calling',
        order: 220,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: "5К КОНКУРЕНТ",
        appType: 'pres',
        type: 'string',
        items: [],
        code: 'op_5k_competitor',
        lead: 'OP_5K_COMPETITOR',
        company: '',
        deal: 'OP_5K_COMPETITOR',
        smart: '',
        task: '',
        app: 'calling',
        order: 220,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: "5К КРИТЕРИИ ВЫБОРА",
        appType: 'pres',
        type: 'string',
        items: [],
        code: 'op_5k_criteria',
        lead: 'OP_5K_CRITERIA',
        company: '',
        deal: 'OP_5K_CRITERIA',
        smart: '',
        task: '',
        app: 'calling',
        order: 220,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Менеджер по продажам Гарант',
        appType: 'general',
        type: 'employee',
        items: [],
        code: 'manager_op',
        lead: 'MANAGER_OP',
        company: 'MANAGER_OP',
        deal: 'MANAGER_OP',
        smart: '',
        task: '',
        app: 'calling',
        order: 220,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Менеджер ТМЦ',
        appType: 'general',
        type: 'employee',
        items: [],
        code: 'manager_tmc',
        lead: 'MANAGER_TMC',
        company: 'MANAGER_TMC',
        deal: 'MANAGER_TMC',
        smart: '',
        task: '',
        app: 'calling',
        order: 220,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Менеджер Отдела Сопровождения',
        appType: 'general',
        type: 'employee',
        items: [],
        code: 'manager_os',
        lead: '',
        company: 'MANAGER_OS',
        deal: 'MANAGER_OS',
        smart: '',
        task: '',
        app: 'calling',
        order: 220,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Менеджер Отдела Обучения',
        appType: 'general',
        type: 'employee',
        items: [],
        code: 'manager_edu',
        lead: 'MANAGER_EDU',
        company: 'MANAGER_EDU',
        deal: 'MANAGER_EDU',
        smart: '',
        task: '',
        app: 'calling',
        order: 220,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП Дата Следующего звонка',
        appType: 'general',
        type: 'datetime',
        items: [],
        code: 'call_next_date',
        lead: 'CALL_NEXT_DATE',
        company: 'CALL_NEXT_DATE',
        deal: 'CALL_NEXT_DATE',
        smart: '',
        task: '',
        app: 'calling',
        order: 220,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП Тема Следующего звонка',
        appType: 'general',
        type: 'string',
        items: [],
        code: 'call_next_name',
        lead: 'CALL_NEXT_NAME',
        company: 'CALL_NEXT_NAME',
        deal: 'CALL_NEXT_NAME',
        smart: '',
        task: '',
        app: 'calling',
        order: 220,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП Дата последнего звонка',
        appType: 'general',
        type: 'datetime',
        items: [],
        code: 'call_last_date',
        lead: 'CALL_LAST_DATE',
        company: 'CALL_LAST_DATE',
        deal: 'CALL_LAST_DATE',
        smart: '',
        task: '',
        app: 'calling',
        order: 220,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Запланировать',
        appType: 'general',
        type: 'boolean',
        items: [],
        code: 'go_plan',
        lead: 'GO_PLAN',
        company: 1696580389,
        deal: 'GO_PLAN',
        smart: '',
        task: '',
        app: 'calling',
        order: 220,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП Текущая история работы',
        appType: 'general',
        type: 'string',
        items: [],
        code: 'op_history',
        lead: 'OP_HISTORY',
        company: 'OP_HISTORY',
        deal: 'OP_HISTORY',
        smart: '',
        task: '',
        app: 'calling',
        order: 220,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП История (Комментарии)',
        appType: 'general',
        type: 'multiple',
        items: [],
        code: 'op_mhistory',
        lead: 'OP_MHISTORY',
        company: 'OP_MHISTORY',
        deal: 'OP_MHISTORY',
        smart: '',
        task: '',
        app: 'calling',
        order: 220,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: true,
    },
    {
        name: 'ОП Статус Работы',
        appType: 'general',
        type: 'enumeration',
        items: [
            { code: 'op_status_in_progress', name: 'В работе (прогресс)' },
            { code: 'op_status_money_await', name: 'Ожидание оплаты' },
            { code: 'op_status_in_work', name: 'В работе' },
            { code: 'op_status_in_long', name: 'Отложено' },
            { code: 'op_status_fail', name: 'Провал' },
            { code: 'op_status_success', name: 'Успех' },
        ],
        code: 'op_work_status',
        lead: 'OP_WORK_STATUS',
        company: 'OP_WORK_STATUS',
        deal: 'OP_WORK_STATUS',
        smart: '',
        task: '',
        app: 'calling',
        order: 230,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП Перспективность Клиента',
        appType: 'fail',
        type: 'enumeration',
        items: [
            { code: 'op_prospects_good', name: 'Перспективная' },
            { code: 'op_prospects_nopersp', name: 'Нет перспектив' },
            { code: 'op_prospects_garant', name: 'Гарант/Запрет' },
            { code: 'op_prospects_go', name: 'Покупает ГО' },
            { code: 'op_prospects_territory', name: 'Чужая территория' },
            { code: 'op_prospects_acountant', name: 'Бухприх' },
            { code: 'op_prospects_autsorc', name: 'Аутсорсинг' },
            {
                code: 'op_prospects_depend',
                name: 'Несамостоятельная организация',
            },
            { code: 'op_prospects_nophone', name: 'Недозвон' },
            { code: 'op_prospects_company', name: 'Компания не существует' },
            { code: 'op_prospects_fail', name: 'Отказ' },
        ],
        code: 'op_prospects_type',
        lead: 'OP_PROSPECTS_TYPE',
        company: 'OP_PROSPECTS_TYPE',
        deal: 'OP_PROSPECTS_TYPE',
        smart: '',
        task: '',
        app: 'calling',
        order: 230,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП Причина Отказа',
        appType: 'calling',
        type: 'enumeration',
        items: [
            { code: 'op_efield_fail_notime', name: 'Не было времени' },
            { code: 'op_efield_fail_c_habit', name: 'Конкуренты - привыкли' },
            { code: 'op_efield_fail_c_prepay', name: 'Конкуренты - оплачено' },
            { code: 'op_efield_fail_c_price', name: 'Конкуренты - цена' },
            { code: 'op_efield_fail_to_expensive', name: 'Слишком дорого' },
            { code: 'op_efield_fail_to_cheap', name: 'Слишком дешево' },
            { code: 'op_efield_fail_nomoney', name: 'Нет денег' },
            { code: 'op_efield_fail_noneed', name: 'Не видят надобности' },
            { code: 'op_efield_fail_lpr', name: 'ЛПР против' },
            {
                code: 'op_efield_fail_employee',
                name: 'Ключевой сотрудник против',
            },
            { code: 'op_efield_fail_off', name: 'Не хотят общаться' },
            {
                code: 'op_efield_fail_off',
                name: 'Не хотят общаться',
            },
            // {
            //     code: 'op_efield_fail_offasdasdsadasdasdsad',
            //     name: 'asdsadasdasdasdasd',
            // },
            // {
            //     code: 'op_efield_fail_offasdasdsadaasdasdsadsdasdd',
            //     name: 'фывыфвыфвфывфыв',
            // },
        ],
        code: 'op_efield_fail_reason',
        lead: 'OP_EFIELD_FAIL_REASON',
        company: 'OP_EFIELD_FAIL_REASON',
        deal: 'OP_EFIELD_FAIL_REASON',
        smart: '',
        task: '',
        app: 'calling',
        order: 230,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП Комментарии после отказов',
        appType: 'fail',
        type: 'multiple',
        items: [],
        code: 'op_fail_comments',
        lead: 'OP_FAIL_COMMENTS',
        company: 'OP_FAIL_COMMENTS',
        deal: 'OP_FAIL_COMMENTS',
        smart: '',
        task: '',
        app: 'calling',
        order: 230,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: true,
    },
    {
        name: 'ОП Причины нерезультативности',
        appType: 'noresult',
        type: 'enumeration',
        items: [
            { code: 'secretar', name: 'Секретарь' },
            { code: 'nopickup', name: 'Недозвон - трубку не берут' },
            { code: 'nonumber', name: 'Недозвон - номер не существует' },
            { code: 'busy', name: 'Занято' },
            { code: 'notime', name: 'Перенос - не было времени' },
            { code: 'nocontact', name: 'Контактера нет на месте' },
            { code: 'giveup', name: 'Просят оставить свой номер' },
            { code: 'bay', name: 'Не интересует, до свидания' },
            { code: 'wrong', name: 'По телефону отвечает не та организация' },
            { code: 'auto', name: 'Автоответчик' },
        ],
        code: 'op_noresult_reason',
        lead: 'OP_NORESULT_REASON',
        company: 'OP_NORESULT_REASON',
        deal: 'OP_NORESULT_REASON',
        smart: '',
        task: '',
        app: 'calling',
        order: 230,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП Статус Клиента',
        appType: 'general',
        type: 'enumeration',
        items: [
            { code: 'free', name: 'Свободен' },
            { code: 'chok', name: 'ЧОК' },
            { code: 'nok', name: 'НОК' },
            { code: 'ok', name: 'ОК' },
            { code: 'stranger_kup', name: 'Чужой КУП' },
            { code: 'stranger_kupkk', name: 'Чужой КУП КК' },
            { code: 'stranger_kgurp', name: 'Чужой КГУ РП' },
            { code: 'own_kup', name: 'Свой КУП' },
            { code: 'own_kupkk', name: 'Свой КУП КК' },
            { code: 'own_kgurp', name: 'Свой КГУ РП' },
        ],
        code: 'op_client_status',
        lead: 'OP_CLIENT_STATUS',
        company: 'OP_CLIENT_STATUS',
        deal: 'OP_CLIENT_STATUS',
        smart: '',
        task: '',
        app: 'calling',
        order: 230,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП Пргноз работы',
        appType: 'general',
        type: 'enumeration',
        items: [
            { code: 'red', name: 'Красный' },
            { code: 'yellow', name: 'Желтый' },
            { code: 'green', name: 'Зеленый' },
        ],
        code: 'op_prospects',
        lead: 'OP_PROSPECTS',
        company: 'OP_PROSPECTS',
        deal: 'OP_PROSPECTS',
        smart: '',
        task: '',
        app: 'calling',
        order: 230,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Тип Клиента',
        appType: 'general',
        type: 'enumeration',
        items: [
            { code: 'state', name: 'Бюджетники' },
            { code: 'commerc', name: 'Коммерческие' },
            { code: 'ip', name: 'ИП' },
            { code: 'fiz', name: 'Физ лицо' },
            { code: 'layer', name: 'Адвокаты' },
        ],
        code: 'op_client_type',
        lead: 'OP_CLIENT_TYPE',
        company: 'OP_CLIENT_TYPE',
        deal: 'OP_CLIENT_TYPE',
        smart: '',
        task: '',
        app: 'calling',
        order: 230,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Конкуренты',
        appType: 'general',
        type: 'enumeration',
        items: [
            { code: 'kons_plus', name: 'Консультант+' },
            { code: 'action', name: 'Актион' },
            { code: 'kodex', name: 'Кодекс' },
            { code: 'bitrix', name: '1С' },
            { code: 'kontur', name: 'Контур' },
            { code: 'internet', name: 'Интернет' },
            { code: 'magazine', name: 'Журналы' },
        ],
        code: 'op_concurents',
        lead: 'OP_CONCURENTS',
        company: 'OP_CONCURENTS',
        deal: 'OP_CONCURENTS',
        smart: '',
        task: '',
        app: 'calling',
        order: 230,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Конкуренты',
        appType: 'general',
        type: 'enumeration',
        items: [
            { code: 'kons_plus', name: 'Консультант+' },
            { code: 'action', name: 'Актион' },
            { code: 'kodex', name: 'Кодекс' },
            { code: 'tech_expert', name: 'Техэксперт' },
            { code: 'kontur', name: 'Контур НОРМАТИВ' },
            { code: 'bitrix', name: '1С ИТС' },
            { code: 'my_business', name: 'Мое дело' },
            { code: 'case_look', name: 'CaseLook' },
            { code: 'audar_info', name: 'Аюдар-Инфо' },
            { code: 'internet', name: 'Интернет' },
            { code: 'magazine', name: 'Журналы' },
            { code: 'other', name: 'Другое' },
        ],
        code: 'op_concurents_multiple',
        lead: 'OP_CONCURENTS_MULTIPLE',
        company: 'OP_CONCURENTS_MULTIPLE',
        deal: 'OP_CONCURENTS_MULTIPLE',
        smart: '',
        task: '',
        app: 'calling',
        order: 230,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: true,
    },
    {
        name: 'Что известно о конкурентах',
        appType: 'general',
        type: 'enumeration',
        items: [
            {
                value: 'Отказались',
                del: 'N',
                xml_id: 'fail',
                code: 'fail',
                sort: 10,
            },
            {
                value: 'Обслуживаются',
                del: 'N',
                xml_id: 'success',
                code: 'success',
                sort: 20,
            },
            {
                value: 'Неизвестно',
                del: 'N',
                xml_id: 'xz',
                code: 'xz',
                sort: 30,
            },
        ] as const,
        code: 'supply_information',
        lead: 'SUPPLY_INFORMATION',
        company: 'SUPPLY_INFORMATION',
        deal: 'SUPPLY_INFORMATION',
        smart: '',
        task: '',
        app: 'calling',
        order: 230,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Категории',
        appType: 'general',
        type: 'enumeration',
        items: [
            { code: 'kkk', name: 'ККК' },
            { code: 'kk', name: 'КК' },
            { code: 'vip', name: 'VIP' },
            { code: 'k', name: 'К' },
            { code: 'c', name: 'С' },
            { code: 'm', name: 'М' },
        ],
        code: 'op_category',
        lead: 'OP_CATEGORY',
        company: 'OP_CATEGORY',
        deal: 'OP_CATEGORY',
        smart: '',
        task: '',
        app: 'calling',
        order: 230,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'companyId',
        appType: 'general',
        type: 'string',
        items: [],
        code: 'op_smart_company_id',
        lead: '',
        company: '',
        deal: 'OP_SMART_COMPANY_ID',
        smart: '',
        task: '',
        app: 'calling',
        order: 230,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'smartId',
        appType: 'general',
        type: 'string',
        items: [],
        code: 'op_smart_id',
        lead: 'OP_SMART_ID',
        company: 'OP_SMART_ID',
        deal: 'OP_SMART_ID',
        smart: '',
        task: '',
        app: 'calling',
        order: 230,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'lidId',
        appType: 'general',
        type: 'string',
        items: [],
        code: 'op_smart_lid',
        lead: 'OP_SMART_LID',
        company: 'OP_SMART_LID',
        deal: 'OP_SMART_LID',
        smart: '',
        task: '',
        app: 'calling',
        order: 230,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: "lidId's",
        appType: 'general',
        type: 'multiple',
        items: [],
        code: 'op_smart_lids',
        lead: 'OP_SMART_LIDS',
        company: 'OP_SMART_LIDS',
        deal: 'OP_SMART_LIDS',
        smart: '',
        task: '',
        app: 'calling',
        order: 230,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: true,
    },
    {
        name: 'Сумма предложения',
        appType: 'only_deals',
        type: 'money',
        items: [],
        code: 'offer_sum',
        lead: 'OFFER_SUM',
        company: 'OFFER_SUM',
        deal: 'OFFER_SUM',
        smart: '',
        task: '',
        app: 'calling',
        order: 240,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Корневая сделка Продажи',
        appType: 'only_deals',
        type: 'crm',
        items: [],
        code: 'to_base_sales',
        lead: 'TO_BASE_SALES',
        company: 'TO_BASE_SALES',
        deal: 'TO_BASE_SALES',
        smart: 'TO_BASE_SALES',
        task: '',
        app: 'calling',
        order: 240,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Сделка ХО Продажи',
        appType: 'only_deals',
        type: 'crm',
        items: [],
        code: 'to_xo_sales',
        lead: 'TO_XO_SALES',
        company: 'TO_XO_SALES',
        deal: 'TO_XO_SALES',
        smart: '',
        task: '',
        app: 'calling',
        order: 240,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Сделка Презентации Продажи',
        appType: 'only_deals',
        type: 'crm',
        items: [],
        code: 'to_presentation_sales',
        lead: 'TO_PRESENTATION_SALES',
        company: 'TO_PRESENTATION_SALES',
        deal: 'TO_PRESENTATION_SALES',
        smart: '',
        task: '',
        app: 'calling',
        order: 240,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Корневая сделка ТМЦ',
        appType: 'only_deals',
        type: 'crm',
        items: [],
        code: 'to_base_tmc',
        lead: 'TO_BASE_TMC',
        company: 'TO_BASE_TMC',
        deal: 'TO_BASE_TMC',
        smart: '',
        task: '',
        app: 'calling',
        order: 240,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Сделка Презентации ТМЦ',
        appType: 'only_deals',
        type: 'crm',
        items: [],
        code: 'to_presentation_tmc',
        lead: 'TO_PRESENTATION_TMC',
        company: 'TO_PRESENTATION_TMC',
        deal: 'TO_PRESENTATION_TMC',
        smart: '',
        task: '',
        app: 'calling',
        order: 240,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Корневая сделка Сервис',
        appType: 'only_deals',
        type: 'crm',
        items: [],
        code: 'to_base_service',
        lead: 'TO_BASE_SERVICE',
        company: 'TO_BASE_SERVICE',
        deal: 'TO_BASE_SERVICE',
        smart: '',
        task: '',
        app: 'calling',
        order: 240,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП Текущий статус',
        appType: 'op_current_status',
        type: 'string',
        items: [],
        code: 'op_current_status',
        lead: 'OP_CURRENT_STATUS',
        company: 'OP_CURRENT_STATUS',
        deal: 'OP_CURRENT_STATUS',
        smart: '',
        task: '',
        app: 'calling',
        order: 230,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП Результат',
        appType: 'calling',
        type: 'enumeration',
        items: [
            {
                value: 'Гарант/ Запрет',
                del: 'N',
                xml_id: 'op_prospects_garant',
                code: 'op_prospects_garant',
                sort: 11,
            },
            {
                value: 'Должники',
                del: 'N',
                xml_id: 'op_result_debts',
                code: 'op_result_debts',
                sort: 12,
            },
            {
                value: 'Заявка',
                del: 'N',
                xml_id: 'op_result_init',
                code: 'op_result_init',
                sort: 13,
            },
            {
                value: 'Клиенты',
                del: 'N',
                xml_id: 'op_result_clients',
                code: 'op_result_clients',
                sort: 14,
            },
            {
                value: 'Конкурент',
                del: 'N',
                xml_id: 'op_result_concurents',
                code: 'op_result_concurents',
                sort: 15,
            },
            {
                value: 'Неверный контакт',
                del: 'N',
                xml_id: 'op_result_fake',
                code: 'op_result_fake',
                sort: 16,
            },
            {
                value: 'Нет финансирования',
                del: 'N',
                xml_id: 'op_result_nofinance',
                code: 'op_result_nofinance',
                sort: 17,
            },
            {
                value: 'Нет_ перспектив',
                del: 'N',
                xml_id: 'op_prospects_nopersp',
                code: 'op_prospects_nopersp',
                sort: 18,
            },
            {
                value: 'Новое',
                del: 'N',
                xml_id: 'op_result_new',
                code: 'op_result_new',
                sort: 19,
            },
            {
                value: 'Отказ',
                del: 'N',
                xml_id: 'op_prospects_fail',
                code: 'op_prospects_fail',
                sort: 20,
            },
            {
                value: 'Отключенные',
                del: 'N',
                xml_id: 'op_result_exclient',
                code: 'op_result_exclient',
                sort: 21,
            },
            {
                value: 'Переговоры',
                del: 'N',
                xml_id: 'op_result_warm',
                code: 'op_result_warm',
                sort: 22,
            },
            {
                value: 'Перенос',
                del: 'N',
                xml_id: 'op_result_pound',
                code: 'op_result_pound',
                sort: 23,
            },
            {
                value: 'Пересечение',
                del: 'N',
                xml_id: 'op_result_other_partner',
                code: 'op_result_other_partner',
                sort: 24,
            },
            {
                value: 'Покупает ГО',
                del: 'N',
                xml_id: 'op_prospects_go',
                code: 'op_prospects_go',
                sort: 25,
            },
            {
                value: 'Пользователи',
                del: 'N',
                xml_id: 'op_prospects_users',
                code: 'op_prospects_users',
                sort: 26,
            },
            {
                value: 'Потерявшиеся/Закрывшиеся',
                del: 'N',
                xml_id: 'op_prospects_company',
                code: 'op_prospects_company',
                sort: 27,
            },
            {
                value: 'Пред. договоренность',
                del: 'N',
                xml_id: 'op_result_prewarm',
                code: 'op_result_prewarm',
                sort: 28,
            },
            {
                value: 'Прозвон ТМЦ',
                del: 'N',
                xml_id: 'op_result_tmc',
                code: 'op_result_tmc',
                sort: 29,
            },
            {
                value: 'Секретарь не пропускает',
                del: 'N',
                xml_id: 'secretar',
                code: 'secretar',
                sort: 30,
            },
            {
                value: 'ТНО/ТПЗ',
                del: 'N',
                xml_id: 'op_result_tnotpz',
                code: 'op_result_tnotpz',
                sort: 31,
            },
            {
                value: 'чужая территория',
                del: 'N',
                xml_id: 'op_prospects_territory',
                code: 'op_prospects_territory',
                sort: 34,
            },
            {
                value: 'Шанс',
                del: 'N',
                xml_id: 'op_result_chance',
                code: 'op_result_chance',
                sort: 35,
            },
        ] as const,
        code: 'op_work_result',
        lead: 'OP_WORK_RESULT',
        company: 'OP_WORK_RESULT',
        deal: 'OP_WORK_RESULT',
        smart: '',
        task: '',
        app: 'calling',
        order: 700,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП Результат',
        appType: 'general',
        type: 'string',
        items: [],
        code: 'op_work_result_string',
        lead: 'OP_WORK_RESULT_STRING',
        company: 'OP_WORK_RESULT_STRING',
        deal: 'OP_WORK_RESULT_STRING',
        smart: '',
        task: '',
        app: 'calling',
        order: 700,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Отдел',
        appType: 'calling',
        type: 'enumeration',
        items: [
            {
                value: 'ТМЦ',
                del: 'N',
                xml_id: 'dep_tmc',
                code: 'dep_tmc',
                sort: 10,
            },
            {
                value: 'Отдел продаж',
                del: 'N',
                xml_id: 'dep_sales',
                code: 'dep_sales',
                sort: 20,
            },
            {
                value: 'Отдел Сервиса',
                del: 'N',
                xml_id: 'dep_service',
                code: 'dep_service',
                sort: 30,
            },
            {
                value: 'Буфер',
                del: 'N',
                xml_id: 'dep_buffer',
                code: 'dep_buffer',
                sort: 40,
            },
        ] as const,
        code: 'department',
        lead: 'DEPARTMENT',
        company: 'DEPARTMENT',
        deal: 'DEPARTMENT',
        smart: '',
        task: '',
        app: 'calling',
        order: 701,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Источник',
        appType: 'calling',
        type: 'string',
        items: [],
        code: 'client_source',
        lead: 'CLIENT_SOURCE',
        company: 'CLIENT_SOURCE',
        deal: 'CLIENT_SOURCE',
        smart: '',
        task: '',
        app: 'calling',
        order: 702,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Источник список',
        appType: 'calling',
        type: 'enumeration',
        items: [
            {
                value: 'Заявка с сайта',
                del: 'N',
                xml_id: 'op_source_1',
                code: 'op_source_1',
                sort: 10,
            },
            {
                value: 'Интернет',
                del: 'N',
                xml_id: 'op_source_2',
                code: 'op_source_2',
                sort: 20,
            },
            {
                value: '2ГИС',
                del: 'N',
                xml_id: 'op_source_3',
                code: 'op_source_3',
                sort: 30,
            },
            {
                value: 'Сайт закупки',
                del: 'N',
                xml_id: 'op_source_4',
                code: 'op_source_4',
                sort: 40,
            },
            {
                value: 'Восстановление',
                del: 'N',
                xml_id: 'op_source_5',
                code: 'op_source_5',
                sort: 50,
            },
            {
                value: 'Платная база',
                del: 'N',
                xml_id: 'op_source_6',
                code: 'op_source_6',
                sort: 60,
            },
            {
                value: 'Семинар',
                del: 'N',
                xml_id: 'op_source_7',
                code: 'op_source_7',
                sort: 70,
            },
        ] as const,
        code: 'op_source_select',
        lead: 'OP_SOURCE_SELECT',
        company: 'OP_SOURCE_SELECT',
        deal: 'OP_SOURCE_SELECT',
        smart: '',
        task: '',
        app: 'calling',
        order: 703,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Конкуренты договор до',
        appType: 'calling',
        type: 'date',
        items: [],
        code: 'op_concurent_contract_date',
        lead: 'OP_CONCURENT_CONTRACT_DATE',
        company: 'OP_CONCURENT_CONTRACT_DATE',
        deal: 'OP_CONCURENT_CONTRACT_DATE',
        smart: '',
        task: '',
        app: 'calling',
        order: 703,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Конкуренты оплачено до',
        appType: 'calling',
        type: 'date',
        items: [],
        code: 'op_concurent_pay_date',
        lead: 'OP_CONCURENT_PAY_DATE',
        company: 'OP_CONCURENT_PAY_DATE',
        deal: 'OP_CONCURENT_PAY_DATE',
        smart: '',
        task: '',
        app: 'calling',
        order: 703,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        // Плановая дата покупки — по владельческой таблице install
        // (front todo2508, строка 418): фильтровое поле компании и сделки.
        name: 'ОП Плановая дата покупки',
        appType: 'calling',
        type: 'date',
        items: [],
        code: 'op_sale_date_prognoz',
        lead: '',
        company: 'OP_SALE_DATE_PROGNOZ',
        deal: 'OP_SALE_DATE_PROGNOZ',
        smart: '',
        task: '',
        app: 'calling',
        order: 703,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        // Чек-лист перехода «Клиент на решении» (2408): дата звонка по
        // решению «выдернута из Хвоста» в отдельное фича-поле — по нему
        // строятся фильтры. Коды и сущности xvost-блока — по владельческой
        // таблице install (todo2508): префикс op_xvost_*, ТОЛЬКО сделка.
        name: 'ОП Дата звонка по решению',
        appType: 'calling',
        type: 'date',
        items: [],
        code: 'op_xvost_decision_call_date',
        lead: '',
        company: '',
        deal: 'OP_XVOST_DECISION_CALL_DATE',
        smart: '',
        task: '',
        app: 'calling',
        order: 704,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    /*
     * «На доработке» — состояние сделки ВНЕ стадий (02.09.2026). У части
     * порталов стадии «Доработка» в воронке нет, а признак показывать и
     * обслуживать нужно. Только сделка — как в Excel calling_fields
     * (order 701). Пишет event-report (applyRefineState модели полей,
     * политики planFlag/planEnteredAt/planReason):
     *  - вход — план «Доработка» или перенос задачи «Доработка»: флаг 1,
     *    дата входа (повторный план без выхода её не двигает), причина —
     *    только в пустое поле (набранное менеджером не перекрывается;
     *    фолбэк — возражения, иначе комментарий отчёта);
     *  - выход — планы «Решение»/«Оплата»/«Поставка», холодный план,
     *    финал (продажа/отказ/не ЦА): все три поля пусты;
     *  - «Документы», «Звонок», «Презентация», отчёт без плана — не трогают.
     */
    {
        name: 'На доработке ?',
        appType: 'refine',
        type: 'boolean',
        items: [],
        code: 'op_is_in_refine',
        lead: '',
        company: '',
        deal: 'OP_IS_IN_REFINE',
        smart: '',
        task: '',
        app: 'calling',
        order: 701,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'На доработке с',
        appType: 'refine',
        type: 'date',
        items: [],
        code: 'op_refined_at',
        lead: '',
        company: '',
        deal: 'OP_REFINED_AT',
        smart: '',
        task: '',
        app: 'calling',
        order: 701,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Почему на доработке - причина',
        appType: 'refine',
        type: 'string',
        items: [],
        code: 'op_refined_reason',
        lead: '',
        company: '',
        deal: 'OP_REFINED_REASON',
        smart: '',
        task: '',
        app: 'calling',
        order: 701,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    /*
     * ЗДЕСЬ БЫЛИ пять полей «Хвоста», ушедших из состава 01.09.2026:
     * согласование даты по решению, дата похода к руководителю и три
     * галочки (КП предложено / наполнение озвучено / цена озвучена).
     *
     * Галочки растворились в связном тексте «ЧТО ПРЕДЛОЖИЛИ»
     * (op_xvost_offered ниже) — сменился и смысл, и ТИП поля. Из дат
     * осталась одна: op_xvost_decision_call_date выше.
     */
    {
        // Связи «Звонки По решению» — элементы будущего ЗПР-смарта
        // (концепция front/docs/zpr-smart-concept.md). Пока только реестр.
        name: 'Звонки По решению',
        appType: 'pres',
        type: 'crm',
        items: [],
        code: 'op_zprs',
        lead: '',
        company: 'OP_ZPRS',
        deal: 'OP_ZPRS',
        smart: '',
        task: '',
        app: 'calling',
        order: 710,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: true,
    },
    {
        // Связи «Презентации» — элементы смарта pres_sales (зеркало сделок
        // «ОП Презентации», libs/portal-lib/pbx/pbx-presentation-smart).
        // Обратная ссылка на элемент: `T{hex(entityTypeId)}_{id}` —
        // presentation-flow дописывает её в сделку и компанию. Пара к
        // op_zprs: тот же контур, только про презентации.
        name: 'Презентации',
        appType: 'pres',
        type: 'crm',
        items: [],
        code: 'op_presentations',
        lead: '',
        company: 'OP_PRESENTATIONS',
        deal: 'OP_PRESENTATIONS',
        smart: '',
        task: '',
        app: 'calling',
        order: 710,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: true,
    },
    {
        // Дата следующего звонка после ОТКАЗА (withPostFail-порталы):
        // перебивает интервал реанимации отказников (sales-hooks/reject-revive).
        name: 'ОП Дата звонка после отказа',
        appType: 'fail',
        type: 'date',
        items: [],
        code: 'post_fail_date',
        lead: '',
        company: '',
        deal: 'POST_FAIL_DATE',
        smart: '',
        task: '',
        app: 'calling',
        order: 711,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        // Маркеры реанимации отказников (двухфазная подстраховка):
        // queued_at ставится ДО отправки cold-call хука — упавший хук
        // оставляет сделку «недоехавшей», и чек-крон досылает её.
        name: 'ОП Реанимация: взято в очередь',
        appType: 'fail',
        type: 'datetime',
        items: [],
        code: 'op_xo_revive_queued_at',
        lead: '',
        company: '',
        deal: 'OP_XO_REVIVE_QUEUED_AT',
        smart: '',
        task: '',
        app: 'calling',
        order: 712,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        // Пара к queued_at: cold-call хук принят буфером — повторно не шлём.
        name: 'ОП Реанимация: хук отправлен',
        appType: 'fail',
        type: 'datetime',
        items: [],
        code: 'op_xo_revive_sent_at',
        lead: '',
        company: '',
        deal: 'OP_XO_REVIVE_SENT_AT',
        smart: '',
        task: '',
        app: 'calling',
        order: 713,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        // Счётчик переносов события (todo2508-02 №6): сколько раз менеджер
        // переносил текущий шаг («Не очень» → новая дата). Инкрементирует
        // event-report в ветке переноса: ХО-сделка при холодном контексте,
        // основная — при остальных типах (DealMoveCountService). Смарты
        // Презентаций/ЗПР считаются отдельно, поэтому поле ТОЛЬКО сделочное.
        name: 'ОП Количество переносов',
        appType: 'calling',
        type: 'integer',
        items: [],
        code: 'op_move_count',
        lead: '',
        company: '',
        deal: 'OP_MOVE_COUNT',
        smart: '',
        task: '',
        app: 'calling',
        order: 714,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },

    // === Граф связей «лид ↔ сделка» + пакет op_lead_* (2026-08, b2b-flow) ===
    // Зеркало листа calling_fields (строки 73-89 + to_sale_deal):
    // связи сделки с лидами живут в НАШИХ полях, штатная конвертация — сигнал.
    {
        name: 'Лид из которого была создана сделка',
        appType: 'lead',
        type: 'crm',
        items: [],
        code: 'deal_from_lead_id',
        lead: '',
        company: '',
        deal: 'DEAL_FROM_LEAD_ID',
        smart: '',
        task: '',
        app: 'calling',
        order: 660,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Лиды присоединенные к сделке',
        appType: 'lead',
        type: 'crm',
        items: [],
        code: 'deal_joined_leads',
        lead: '',
        company: '',
        deal: 'DEAL_JOINED_LEADS',
        smart: '',
        task: '',
        app: 'calling',
        order: 660,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: true,
    },
    {
        // Зеркало установленной строки Excel: поле стоит на лиде, компании,
        // сделке и смарте; хранит ССЫЛКУ НА СДЕЛКУ (crmEntities='deal').
        name: 'Связанная продажа',
        appType: 'only_deals',
        type: 'crm',
        items: [],
        code: 'to_sale_deal',
        lead: 'TO_SALE_DEAL',
        company: 'TO_SALE_DEAL',
        deal: 'TO_SALE_DEAL',
        smart: 'TO_SALE_DEAL',
        task: '',
        app: 'calling',
        order: 576,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Статус Лида',
        appType: 'lead',
        type: 'enumeration',
        items: [
            { code: 'op_lead_status_one', name: 'Создан' },
            { code: 'op_lead_status_two', name: 'Определен ОП' },
            { code: 'op_lead_status_three', name: 'Передан сотруднику' },
            { code: 'op_lead_status_four', name: 'Работа со сделкой' },
            { code: 'op_lead_status_five', name: 'Работа с компанией' },
            { code: 'op_lead_status_six', name: 'Презентации' },
            { code: 'op_lead_status_seven', name: 'Документы' },
            { code: 'op_lead_status_eight', name: 'Продажа' },
            { code: 'op_lead_status_nine', name: 'Отказ' },
            { code: 'op_lead_status_ten', name: 'Не ца' },
        ],
        code: 'op_lead_status',
        lead: 'OP_LEAD_STATUS',
        company: '',
        deal: '',
        smart: '',
        task: '',
        app: 'calling',
        order: 660,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Статус Заявки',
        appType: 'lead',
        type: 'enumeration',
        items: [
            { code: 'op_lead_site_status1', name: 'Повявилась' },
            { code: 'op_lead_site_status2', name: 'Взята в работу' },
            { code: 'op_lead_site_status3', name: 'Не ЦА' },
            { code: 'op_lead_site_status4', name: 'Ведется активная работа' },
            { code: 'op_lead_site_status5', name: 'Отказ' },
            // Единая ось заявки (2408): автоматика из отчётов, руками не
            // ставятся. Items новые — добить install на порталах.
            { code: 'op_lead_site_status6', name: 'Первый звонок' },
            { code: 'op_lead_site_status7', name: 'Дозвонились' },
            { code: 'op_lead_site_status8', name: 'Презентация' },
            { code: 'op_lead_site_status9', name: 'Продажа' },
        ],
        code: 'op_lead_site_status',
        lead: 'OP_LEAD_SITE_STATUS',
        company: '',
        deal: '',
        smart: '',
        task: '',
        app: 'calling',
        order: 660,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Стадия Заявки',
        appType: 'lead',
        type: 'enumeration',
        items: [
            { code: 'op_lead_site_stage1', name: 'Назначена менеджеру' },
            { code: 'op_lead_site_stage2', name: 'Взята в работу' },
            { code: 'op_lead_site_stage3', name: 'Запланирован звонок' },
            { code: 'op_lead_site_stage4', name: 'Проведена презентация' },
            { code: 'op_lead_site_stage5', name: 'Установлена компания' },
            {
                code: 'op_lead_site_stage6',
                name: 'Есть ИНН/Проверено на дубли',
            },
            {
                code: 'op_lead_site_stage7',
                name: 'Работа уже велась - присоеденили',
            },
            { code: 'op_lead_site_stage8', name: 'Отказ' },
            { code: 'op_lead_site_stage9', name: 'Продажа' },
        ],
        code: 'op_lead_site_stage',
        lead: 'OP_LEAD_SITE_STAGE',
        company: '',
        deal: '',
        smart: '',
        task: '',
        app: 'calling',
        order: 660,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    /*
     * Вид работы по лиду — НАШ признак, которым управляем только мы.
     *
     * Пишется хуком «лид → работа» в момент передачи лида в работу (рядом с
     * `op_lead_assigned_at`) и дальше служит источником истины: от него
     * зависит слово в заголовке задачи («Заявка»/«Лид»), а значит и тип
     * события во фрейме, и код события в KPI.
     *
     * Почему своё поле, а не штатный `SOURCE_ID`: источник — чужое поле,
     * его правят руками и настраивают на каждом портале по-своему, поэтому
     * держать на нём вид работы нельзя. Наше поле переживает и ручные
     * правки источника, и разницу настроек порталов.
     */
    {
        name: 'ОП Вид работы по лиду',
        appType: 'lead',
        type: 'enumeration',
        items: [
            { code: 'op_lead_work_kind1', name: 'Холодный' },
            { code: 'op_lead_work_kind2', name: 'Заявка' },
            { code: 'op_lead_work_kind3', name: 'Лид' },
        ],
        code: 'op_lead_work_kind',
        lead: 'OP_LEAD_WORK_KIND',
        company: '',
        deal: '',
        smart: '',
        task: '',
        app: 'calling',
        // Зеркало факта установки на портале (garantservisvoronezh, SORT 702).
        order: 702,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Стадия Связанной сделки',
        appType: 'lead',
        type: 'enumeration',
        items: [
            { code: 'op_leads_related_base_stage1', name: 'Холодные' },
            { code: 'op_leads_related_base_stage2', name: 'В работе' },
            { code: 'op_leads_related_base_stage3', name: 'Презентация' },
            { code: 'op_leads_related_base_stage4', name: 'Документы' },
            { code: 'op_leads_related_base_stage5', name: 'В решении' },
            { code: 'op_leads_related_base_stage6', name: 'В оплате' },
            { code: 'op_leads_related_base_stage7', name: 'Продажа' },
            { code: 'op_leads_related_base_stage8', name: 'Отказ' },
            { code: 'op_leads_related_base_stage9', name: 'Дубль' },
        ],
        code: 'op_leads_related_base_stage',
        lead: 'OP_LEADS_RELATED_BASE_STAGE',
        company: '',
        deal: '',
        smart: '',
        task: '',
        app: 'calling',
        order: 660,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'НЕ ЦА ТИП',
        appType: 'lead',
        type: 'enumeration',
        items: [
            { code: 'op_lead_not_ca_type1', name: 'Квартира' },
            { code: 'op_lead_not_ca_type2', name: 'Не существует телефон' },
            { code: 'op_lead_not_ca_type3', name: 'Компания не существует' },
            { code: 'op_lead_not_ca_type4', name: 'Нет специалистов' },
        ],
        code: 'op_lead_not_ca_type',
        lead: 'OP_LEAD_NOT_CA_TYPE',
        // Компания и сделка — по владельческой таблице install (todo2508):
        // при «не ЦА» тип пишется и в них (event-report entity-fields).
        company: 'OP_LEAD_NOT_CA_TYPE',
        deal: 'OP_LEAD_NOT_CA_TYPE',
        smart: '',
        task: '',
        app: 'calling',
        order: 660,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Статус не звонить никогда',
        appType: 'lead',
        type: 'boolean',
        items: [],
        code: 'op_lead_is_black_short',
        lead: 'OP_LEAD_IS_BLACK_SHORT',
        company: '',
        deal: '',
        smart: '',
        task: '',
        app: 'calling',
        order: 660,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Причина',
        appType: 'lead',
        type: 'string',
        items: [],
        code: 'op_lead_black_short_reason',
        lead: 'OP_LEAD_BLACK_SHORT_REASON',
        company: '',
        deal: '',
        smart: '',
        task: '',
        app: 'calling',
        order: 660,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Время обработки заяки',
        appType: 'lead',
        type: 'integer',
        items: [],
        code: 'op_lead_firstprepare_long',
        lead: 'OP_LEAD_FIRSTPREPARE_LONG',
        company: '',
        deal: '',
        smart: '',
        task: '',
        app: 'calling',
        order: 660,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    /*
     * Момент НАЗНАЧЕНИЯ заявки менеджеру — старт отсчёта SLA принятия.
     * Пишется хуком при каждом назначении и передаче (таймер стартует
     * заново), очищается принятием. Нужен как надёжная опора вместо
     * DATE_MODIFY: тот сбивается любой правкой карточки, а стадию лида
     * может двинуть кто угодно (конструктор, робот, руками).
     *
     * ⚠ На порталах поле заведено И НА СДЕЛКЕ, поэтому маппинг здесь есть —
     * реестр обязан отражать реальность. Но бэк пишет и читает ТОЛЬКО
     * лидовую копию: «ждёт подтверждения» обязан иметь ОДИН источник, иначе
     * фрейм и SLA-крон разъедутся. Все потребители лид-скоупные:
     * `LeadRequestService.isAccepted`, `LeadRequestSlaService`,
     * `LeadRequestAcceptService`, `LeadIntakeRescueService`,
     * `LeadXoEventEntityModel`.
     * Копия на сделке (решение владельца, todo2508): таймер работы по сделке.
     * Ставит deal-work-timer.util (передача работы + создание сделки из лида
     * хуком lead-to-work), снимает принятие (LeadRequestAcceptService),
     * страхует SLA-проход по сделкам.
     */
    {
        name: 'Заявка назначена (дата)',
        appType: 'lead',
        type: 'datetime',
        items: [],
        code: 'op_lead_assigned_at',
        lead: 'OP_LEAD_ASSIGNED_AT',
        company: '',
        deal: 'OP_LEAD_ASSIGNED_AT',
        smart: '',
        task: '',
        app: 'calling',
        // Зеркало факта установки на портале (SORT 701).
        order: 701,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'История Обработки заяки',
        appType: 'lead',
        type: 'multiple',
        items: [],
        code: 'op_lead_firstprepare_history',
        lead: 'OP_LEAD_FIRSTPREPARE_HISTORY',
        company: '',
        deal: '',
        smart: '',
        task: '',
        app: 'calling',
        order: 660,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: true,
    },
    {
        name: 'Установлена комания',
        appType: 'lead',
        type: 'boolean',
        items: [],
        code: 'op_lead_is_company',
        lead: 'OP_LEAD_IS_COMPANY',
        company: '',
        deal: '',
        smart: '',
        task: '',
        app: 'calling',
        order: 660,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Отправлен Отчет в НПП',
        appType: 'lead',
        type: 'boolean',
        items: [],
        code: 'op_lead_is_npp_repoted',
        lead: 'OP_LEAD_IS_NPP_REPOTED',
        company: '',
        deal: '',
        smart: '',
        task: '',
        app: 'calling',
        order: 660,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Проверено на дубли (установлен ИНН)',
        appType: 'lead',
        type: 'boolean',
        items: [],
        code: 'op_lead_is_duplicate_check',
        lead: 'OP_LEAD_IS_DUPLICATE_CHECK',
        company: '',
        deal: '',
        smart: '',
        task: '',
        app: 'calling',
        order: 660,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Найдены дубли',
        appType: 'lead',
        type: 'boolean',
        items: [],
        code: 'op_lead_is_duplicate',
        lead: 'OP_LEAD_IS_DUPLICATE',
        company: '',
        deal: '',
        smart: '',
        task: '',
        app: 'calling',
        order: 660,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Присоеденнен к существующей работе',
        appType: 'lead',
        type: 'boolean',
        items: [],
        code: 'op_lead_is_merged_by_exist',
        lead: 'OP_LEAD_IS_MERGED_BY_EXIST',
        company: '',
        deal: '',
        smart: '',
        task: '',
        app: 'calling',
        order: 660,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Повлиял на продажу',
        appType: 'lead',
        type: 'boolean',
        items: [],
        code: 'op_lead_is_boost_sale',
        lead: 'OP_LEAD_IS_BOOST_SALE',
        company: '',
        deal: '',
        smart: '',
        task: '',
        app: 'calling',
        order: 660,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    /*
     * ОФИЦИАЛЬНЫЙ статус заявки в ТПС Гаранта (docs/newfields.md, «Правила
     * оценки заявок»). Это ВНЕШНИЙ словарь — коды семантические, завязаны
     * на документ (не op_..._1..N): партнёр обязан проставить статус в ТПС
     * за 4 рабочих дня, иначе заявка ротируется другому партнёру.
     */
    {
        name: 'Статус заявки ТПС (Гарант)',
        appType: 'lead',
        type: 'enumeration',
        items: [
            { code: 'tps_alien_client', name: 'Чужой клиент' },
            { code: 'tps_alien_territory', name: 'Чужая территория' },
            { code: 'tps_served_client', name: 'Обслуживаемый клиент' },
            { code: 'tps_sale', name: 'Продажа' },
            { code: 'tps_refuse', name: 'Отказ' },
            { code: 'tps_no_answer', name: 'Телефон не отвечает' },
            { code: 'tps_in_work', name: 'В работе' },
            { code: 'tps_reserve', name: 'Бронь' },
        ],
        code: 'op_lead_tps_status',
        lead: 'OP_LEAD_TPS_STATUS',
        company: '',
        deal: '',
        smart: '',
        task: '',
        app: 'calling',
        order: 662,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    // Анкета оценки ТПС, вопрос 1: потребность в СПС в целом.
    {
        name: 'ТПС анкета: потребность в СПС',
        appType: 'lead',
        type: 'enumeration',
        items: [
            { code: 'tps_quest_yes', name: 'Да' },
            { code: 'tps_quest_no', name: 'Нет' },
            { code: 'tps_quest_no_info', name: 'Нет информации' },
        ],
        code: 'op_lead_tps_quest_need',
        lead: 'OP_LEAD_TPS_QUEST_NEED',
        company: '',
        deal: '',
        smart: '',
        task: '',
        app: 'calling',
        order: 663,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    // Анкета оценки ТПС, вопрос 2: заявка оформлена корректно.
    {
        name: 'ТПС анкета: заявка оформлена корректно',
        appType: 'lead',
        type: 'enumeration',
        items: [
            { code: 'tps_quest2_yes', name: 'Да' },
            { code: 'tps_quest2_no', name: 'Нет' },
            { code: 'tps_quest2_no_info', name: 'Нет информации' },
        ],
        code: 'op_lead_tps_quest_valid',
        lead: 'OP_LEAD_TPS_QUEST_VALID',
        company: '',
        deal: '',
        smart: '',
        task: '',
        app: 'calling',
        order: 664,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    /*
     * ВОЗРАЖЕНИЕ клиента — своя пара полей, отдельно от причины отказа.
     *
     * Раньше чек-лист «Доработка» писал возражение в `op_efield_fail_reason`,
     * то есть в поле ПРИЧИНЫ ОТКАЗА, и финальный отказ его перезатирал: два
     * разных смысла в одном поле, и историю «что мешало купить» свести было
     * нельзя. Теперь причина отказа принадлежит ТОЛЬКО финалу, а возражение
     * живёт по своей шкале времени и меняется от звонка к звонку.
     *
     * Состав справочника — тот же, что у `op_efield_fail_reason`: менеджер
     * называет одно и то же одинаково, и связку «возражал → отказался»
     * можно считать только на общей шкале. Коды свои (op_objection_*):
     * item-код уникален в пределах поля и уезжает в Битрикс как xmlId.
     */
    {
        name: 'ОП Возражение клиента',
        appType: 'calling',
        type: 'enumeration',
        items: [
            { code: 'op_objection_notime', name: 'Не было времени' },
            { code: 'op_objection_c_habit', name: 'Конкуренты - привыкли' },
            { code: 'op_objection_c_prepay', name: 'Конкуренты - оплачено' },
            { code: 'op_objection_c_price', name: 'Конкуренты - цена' },
            { code: 'op_objection_to_expensive', name: 'Слишком дорого' },
            { code: 'op_objection_to_cheap', name: 'Слишком дешево' },
            { code: 'op_objection_nomoney', name: 'Нет денег' },
            { code: 'op_objection_noneed', name: 'Не видят надобности' },
            { code: 'op_objection_lpr', name: 'ЛПР против' },
            {
                code: 'op_objection_employee',
                name: 'Ключевой сотрудник против',
            },
            { code: 'op_objection_off', name: 'Не хотят общаться' },
            // «Отжать» возражение: явный ответ «их нет» — отличим от
            // «не спрашивали» и закрывает обязательность (02.09).
            { code: 'op_objection_none', name: 'Нет возражений' },
        ],
        code: 'op_objection_reason',
        lead: 'OP_OBJECTION_REASON',
        company: 'OP_OBJECTION_REASON',
        deal: 'OP_OBJECTION_REASON',
        smart: '',
        task: '',
        app: 'calling',
        order: 720,
        is_rewrite: '',
        isNeedUpdate: true,
        // МНОЖЕСТВЕННОЕ (решение 01.09.2026). На звонке возражений обычно
        // несколько — «дорого» и «нет времени» разом, — и одиночное поле
        // заставляло менеджера выбрать одно, потеряв остальные.
        //
        // Запись — ЗАМЕНОЙ всего набора за звонок, не добавлением: поле
        // отвечает на «что мешает СЕЙЧАС», а накопление за полгода
        // превратило бы его в свалку, где текущего возражения не видно.
        // История «что мешало раньше» и так лежит в оси событий клиента.
        //
        // Парное op_objection_comment остаётся ОДИНОЧНЫМ: это дословная
        // фраза клиента, она одна.
        isMultiple: true,
    },
    {
        // Формулировка клиента СВОИМИ СЛОВАМИ: справочник огрубляет
        // («Нет денег»), а дожимает следующий звонок дословная фраза.
        name: 'ОП Возражение клиента (формулировка)',
        appType: 'calling',
        type: 'string',
        items: [],
        code: 'op_objection_comment',
        lead: 'OP_OBJECTION_COMMENT',
        company: 'OP_OBJECTION_COMMENT',
        deal: 'OP_OBJECTION_COMMENT',
        smart: '',
        task: '',
        app: 'calling',
        order: 721,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    /*
     * РЕШЕНИЕ клиента (todo2508 №13, пункт чек-листа «Решение подтверждено»).
     * Раньше исход звонка по решению жил только в тексте комментария —
     * фильтровать и считать «сколько решений отложено» было нечем.
     *
     * Компании поля нет намеренно: решение принимается по КОНКРЕТНОМУ
     * предложению, то есть по сделке (и по заявке-лиду до неё), а не по
     * клиенту вообще.
     */
    {
        name: 'ОП Исход решения',
        appType: 'calling',
        type: 'enumeration',
        items: [
            { code: 'op_decision_accepted', name: 'Решение принято' },
            { code: 'op_decision_postponed', name: 'Решение отложено' },
            { code: 'op_decision_refused', name: 'Отказ' },
        ],
        code: 'op_decision_outcome',
        lead: 'OP_DECISION_OUTCOME',
        company: '',
        deal: 'OP_DECISION_OUTCOME',
        smart: '',
        task: '',
        app: 'calling',
        order: 722,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        // Дата решения — ТОЛЬКО сделка: она и есть цикл сделки, по ней
        // считается срок «от презентации до решения».
        name: 'ОП Дата решения',
        appType: 'calling',
        type: 'date',
        items: [],
        code: 'op_decision_date',
        lead: '',
        company: '',
        deal: 'OP_DECISION_DATE',
        smart: '',
        task: '',
        app: 'calling',
        order: 723,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    /*
     * «Хвост» — ПЯТЬ текстовых полей плюс дата (переделка 01.09.2026).
     *
     * Что заменено: шесть полей op_talk_* (по одному вопросу в каждом), три
     * галочки op_xvost_is_* и две даты. Галочки стали частью связного
     * текста «ЧТО ПРЕДЛОЖИЛИ», то есть сменился и смысл, и ТИП — переносить
     * старые значения некуда и незачем.
     *
     * Датой осталась одна — op_xvost_decision_call_date (выше): «дата звонка
     * по решению». «Дата подхода к руководителю» и «согласование даты» из
     * состава ушли.
     *
     * Сущности lead+deal, БЕЗ компании — намеренно. У op_talk_* компания
     * была, но не писал в неё никто: шесть вечно пустых полей в карточке.
     * Повторять это в новом составе нет причины.
     *
     * Подвопросы живут ВНУТРИ значения текстом (шаблон — SURVEY_TEMPLATES
     * в shared/presentation-survey) и в подсказке поля.
     */
    {
        name: "ХВОСТ ЖЕЛАНИЕ РАБОТАТЬ С ГАРАНТОМ",
        appType: 'pres',
        type: 'string',
        items: [],
        code: 'op_xvost_desire',
        lead: 'OP_XVOST_DESIRE',
        company: '',
        deal: 'OP_XVOST_DESIRE',
        smart: '',
        task: '',
        app: 'calling',
        order: 724,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: "ХВОСТ ЧТО ПРЕДЛОЖИЛИ",
        appType: 'pres',
        type: 'string',
        items: [],
        code: 'op_xvost_offered',
        lead: 'OP_XVOST_OFFERED',
        company: '',
        deal: 'OP_XVOST_OFFERED',
        smart: '',
        task: '',
        app: 'calling',
        order: 725,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: "ХВОСТ РЕАКЦИЯ НА ЦЕНУ",
        appType: 'pres',
        type: 'string',
        items: [],
        code: 'op_xvost_price_reaction',
        lead: 'OP_XVOST_PRICE_REACTION',
        company: '',
        deal: 'OP_XVOST_PRICE_REACTION',
        smart: '',
        task: '',
        app: 'calling',
        order: 726,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: "ХВОСТ ПРОЦЕСС ПРИНЯТИЯ РЕШЕНИЯ",
        appType: 'pres',
        type: 'string',
        items: [],
        code: 'op_xvost_decision_process',
        lead: 'OP_XVOST_DECISION_PROCESS',
        company: '',
        deal: 'OP_XVOST_DECISION_PROCESS',
        smart: '',
        task: '',
        app: 'calling',
        order: 727,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: "ХВОСТ ВЫХОД НА РЕШЕНИЕ",
        appType: 'pres',
        type: 'string',
        items: [],
        code: 'op_xvost_decision_way',
        lead: 'OP_XVOST_DECISION_WAY',
        company: '',
        deal: 'OP_XVOST_DECISION_WAY',
        smart: '',
        task: '',
        app: 'calling',
        order: 728,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
] as const;

export type PbxSalesEventField = (typeof PBX_SALES_EVENT_FIELDS)[number];
export type PbxSalesEventFieldCode = PbxSalesEventField['code'];

/** Finds a field by `code` with a narrowed literal type (including `items`). */
export function findPbxSalesEventField<const C extends PbxSalesEventFieldCode>(
    code: C,
): Extract<PbxSalesEventField, { code: C }> | undefined {
    return PBX_SALES_EVENT_FIELDS.find(
        (field): field is Extract<PbxSalesEventField, { code: C }> =>
            field.code === code,
    );
}

export type PbxSalesEventFieldType = PbxSalesEventField['type'];
export type PbxSalesEventFieldAppType = PbxSalesEventField['appType'];
export type PbxSalesEventFieldApp = PbxSalesEventField['app'];

export type PbxSalesEventFieldWithItems = FieldWithItems<
    typeof PBX_SALES_EVENT_FIELDS,
    'items'
>;
export type PbxSalesEventFieldWithItemsCode =
    PbxSalesEventFieldWithItems['code'];
export type PbxSalesEventFieldItemCode<
    Code extends PbxSalesEventFieldWithItemsCode,
> = FieldItemCode<typeof PBX_SALES_EVENT_FIELDS, 'items', Code>;
export type PbxSalesEventFieldItemCodesMap = FieldItemCodesMap<
    typeof PBX_SALES_EVENT_FIELDS,
    'items'
>;

export const PBX_SALES_EVENT_FIELD_CODES = Object.freeze(
    createEnumObject(
        PBX_SALES_EVENT_FIELDS.map(
            field => field.code,
        ) as readonly PbxSalesEventFieldCode[],
    ),
);

export const PBX_SALES_EVENT_FIELD_TYPES = Object.freeze(
    createEnumObject(
        PBX_SALES_EVENT_FIELDS.map(
            field => field.type,
        ) as readonly PbxSalesEventFieldType[],
    ),
);

export const PBX_SALES_EVENT_FIELD_APP_TYPES = Object.freeze(
    createEnumObject(
        PBX_SALES_EVENT_FIELDS.map(
            field => field.appType,
        ) as readonly PbxSalesEventFieldAppType[],
    ),
);

export const PBX_SALES_EVENT_FIELD_APPS = Object.freeze(
    createEnumObject(
        PBX_SALES_EVENT_FIELDS.map(
            field => field.app,
        ) as readonly PbxSalesEventFieldApp[],
    ),
);

export const PBX_SALES_EVENT_FIELD_ITEM_CODES = Object.freeze(
    createFieldItemsEnum(PBX_SALES_EVENT_FIELDS, 'items'),
);
