import {
    createEnumObject,
    createFieldItemsEnum,
    FieldItemCode,
    FieldItemCodesMap,
    FieldWithItems,
} from '../../pbx-field-type.util';
export const PBX_SALES_EVENT_FIELDS = [
    {
        name: 'ОП Название ХО',
        appType: 'xo',
        type: 'string',
        items: [],
        code: 'xo_name',
        lead: 'XO_NAME',
        company: 'XO_NAME',
        deal: 'XO_NAME',
        smart: '',
        task: '',
        app: 'calling',
        order: 210,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП Дата Холодного обзвона',
        appType: 'xo',
        type: 'datetime',
        items: [],
        code: 'xo_date',
        lead: 'XO_DATE',
        company: 'XO_DATE',
        deal: 'XO_DATE',
        smart: '',
        task: '',
        app: 'calling',
        order: 210,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП Ответственный ХО',
        appType: 'xo',
        type: 'employee',
        items: [],
        code: 'xo_responsible',
        lead: 'XO_RESPONSIBLE',
        company: 'XO_RESPONSIBLE',
        deal: 'XO_RESPONSIBLE',
        smart: '',
        task: '',
        app: 'calling',
        order: 210,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП Постановщик ХО',
        appType: 'xo',
        type: 'employee',
        items: [],
        code: 'xo_created',
        lead: 'XO_CREATED',
        company: 'XO_CREATED',
        deal: 'XO_CREATED',
        smart: '',
        task: '',
        app: 'calling',
        order: 210,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП Дата назначенной презентации',
        appType: 'pres',
        type: 'datetime',
        items: [],
        code: 'next_pres_plan_date',
        lead: 'NEXT_PRES_PLAN_DATE',
        company: 'NEXT_PRES_PLAN_DATE',
        deal: 'NEXT_PRES_PLAN_DATE',
        smart: '',
        task: '',
        app: 'calling',
        order: 220,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП Дата последней назначенной презентации',
        appType: 'pres',
        type: 'datetime',
        items: [],
        code: 'last_pres_plan_date',
        lead: 'LAST_PRES_PLAN_DATE',
        company: 'LAST_PRES_PLAN_DATE',
        deal: 'LAST_PRES_PLAN_DATE',
        smart: '',
        task: '',
        app: 'calling',
        order: 220,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП Дата последней проведенной презентации',
        appType: 'pres',
        type: 'datetime',
        items: [],
        code: 'last_pres_done_date',
        lead: 'LAST_PRES_DONE_DATE',
        company: 'LAST_PRES_DONE_DATE',
        deal: 'LAST_PRES_DONE_DATE',
        smart: '',
        task: '',
        app: 'calling',
        order: 220,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП Кто назначил последнюю заявку на презентацию',
        appType: 'pres',
        type: 'employee',
        items: [],
        code: 'last_pres_plan_responsible',
        lead: 'LAST_PRES_PLAN_RESPONSIBLE',
        company: 'LAST_PRES_PLAN_RESPONSIBLE',
        deal: 'LAST_PRES_PLAN_RESPONSIBLE',
        smart: '',
        task: '',
        app: 'calling',
        order: 220,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП Кто провел последнюю презентацию',
        appType: 'pres',
        type: 'employee',
        items: [],
        code: 'last_pres_done_responsible',
        lead: 'LAST_PRES_DONE_RESPONSIBLE',
        company: 'LAST_PRES_DONE_RESPONSIBLE',
        deal: 'LAST_PRES_DONE_RESPONSIBLE',
        smart: '',
        task: '',
        app: 'calling',
        order: 220,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП Проведено презентаций',
        appType: 'pres',
        type: 'integer',
        items: [],
        code: 'pres_count',
        lead: 'PRES_COUNT',
        company: 1709807026,
        deal: 'PRES_COUNT',
        smart: '',
        task: '',
        app: 'calling',
        order: 220,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП Комментарии после презентаций',
        appType: 'pres',
        type: 'multiple',
        items: [],
        code: 'pres_comments',
        lead: 'PRES_COMMENTS',
        company: 'PRES_COMMENTS',
        deal: 'PRES_COMMENTS',
        smart: '',
        task: '',
        app: 'calling',
        order: 220,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Менеджер по продажам Гарант',
        appType: 'general',
        type: 'employee',
        items: [],
        code: 'manager_op',
        lead: 'MANAGER_OP',
        company: 'MANAGER_OP',
        deal: 'MANAGER_OP',
        smart: '',
        task: '',
        app: 'calling',
        order: 220,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Менеджер ТМЦ',
        appType: 'general',
        type: 'employee',
        items: [],
        code: 'manager_tmc',
        lead: 'MANAGER_TMC',
        company: 'MANAGER_TMC',
        deal: 'MANAGER_TMC',
        smart: '',
        task: '',
        app: 'calling',
        order: 220,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Менеджер Отдела Сопровождения',
        appType: 'general',
        type: 'employee',
        items: [],
        code: 'manager_os',
        lead: '',
        company: 'MANAGER_OS',
        deal: 'MANAGER_OS',
        smart: '',
        task: '',
        app: 'calling',
        order: 220,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Менеджер Отдела Обучения',
        appType: 'general',
        type: 'employee',
        items: [],
        code: 'manager_edu',
        lead: 'MANAGER_EDU',
        company: 'MANAGER_EDU',
        deal: 'MANAGER_EDU',
        smart: '',
        task: '',
        app: 'calling',
        order: 220,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП Дата Следующего звонка',
        appType: 'general',
        type: 'datetime',
        items: [],
        code: 'call_next_date',
        lead: 'CALL_NEXT_DATE',
        company: 'CALL_NEXT_DATE',
        deal: 'CALL_NEXT_DATE',
        smart: '',
        task: '',
        app: 'calling',
        order: 220,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП Тема Следующего звонка',
        appType: 'general',
        type: 'string',
        items: [],
        code: 'call_next_name',
        lead: 'CALL_NEXT_NAME',
        company: 'CALL_NEXT_NAME',
        deal: 'CALL_NEXT_NAME',
        smart: '',
        task: '',
        app: 'calling',
        order: 220,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП Дата последнего звонка',
        appType: 'general',
        type: 'datetime',
        items: [],
        code: 'call_last_date',
        lead: 'CALL_LAST_DATE',
        company: 'CALL_LAST_DATE',
        deal: 'CALL_LAST_DATE',
        smart: '',
        task: '',
        app: 'calling',
        order: 220,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Запланировать',
        appType: 'general',
        type: 'boolean',
        items: [],
        code: 'go_plan',
        lead: 'GO_PLAN',
        company: 1696580389,
        deal: 'GO_PLAN',
        smart: '',
        task: '',
        app: 'calling',
        order: 220,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП Текущая история работы',
        appType: 'general',
        type: 'string',
        items: [],
        code: 'op_history',
        lead: 'OP_HISTORY',
        company: 'OP_HISTORY',
        deal: 'OP_HISTORY',
        smart: '',
        task: '',
        app: 'calling',
        order: 220,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП История (Комментарии)',
        appType: 'general',
        type: 'multiple',
        items: [],
        code: 'op_mhistory',
        lead: 'OP_MHISTORY',
        company: 'OP_MHISTORY',
        deal: 'OP_MHISTORY',
        smart: '',
        task: '',
        app: 'calling',
        order: 220,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП Статус Работы',
        appType: 'general',
        type: 'enumeration',
        items: [
            { code: 'op_status_in_progress', name: 'В работе (прогресс)' },
            { code: 'op_status_money_await', name: 'Ожидание оплаты' },
            { code: 'op_status_in_work', name: 'В работе' },
            { code: 'op_status_in_long', name: 'Отложено' },
            { code: 'op_status_fail', name: 'Провал' },
            { code: 'op_status_success', name: 'Успех' },
        ],
        code: 'op_work_status',
        lead: 'OP_WORK_STATUS',
        company: 'OP_WORK_STATUS',
        deal: 'OP_WORK_STATUS',
        smart: '',
        task: '',
        app: 'calling',
        order: 230,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП Перспективность Клиента',
        appType: 'fail',
        type: 'enumeration',
        items: [
            { code: 'op_prospects_good', name: 'Перспективная' },
            { code: 'op_prospects_nopersp', name: 'Нет перспектив' },
            { code: 'op_prospects_garant', name: 'Гарант/Запрет' },
            { code: 'op_prospects_go', name: 'Покупает ГО' },
            { code: 'op_prospects_territory', name: 'Чужая территория' },
            { code: 'op_prospects_acountant', name: 'Бухприх' },
            { code: 'op_prospects_autsorc', name: 'Аутсорсинг' },
            {
                code: 'op_prospects_depend',
                name: 'Несамостоятельная организация',
            },
            { code: 'op_prospects_nophone', name: 'Недозвон' },
            { code: 'op_prospects_company', name: 'Компания не существует' },
            { code: 'op_prospects_fail', name: 'Отказ' },
        ],
        code: 'op_prospects_type',
        lead: 'OP_PROSPECTS_TYPE',
        company: 'OP_PROSPECTS_TYPE',
        deal: 'OP_PROSPECTS_TYPE',
        smart: '',
        task: '',
        app: 'calling',
        order: 230,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП Причина Отказа',
        appType: 'calling',
        type: 'enumeration',
        items: [
            { code: 'op_efield_fail_notime', name: 'Не было времени' },
            { code: 'op_efield_fail_c_habit', name: 'Конкуренты - привыкли' },
            { code: 'op_efield_fail_c_prepay', name: 'Конкуренты - оплачено' },
            { code: 'op_efield_fail_c_price', name: 'Конкуренты - цена' },
            { code: 'op_efield_fail_to_expensive', name: 'Слишком дорого' },
            { code: 'op_efield_fail_to_cheap', name: 'Слишком дешево' },
            { code: 'op_efield_fail_nomoney', name: 'Нет денег' },
            { code: 'op_efield_fail_noneed', name: 'Не видят надобности' },
            { code: 'op_efield_fail_lpr', name: 'ЛПР против' },
            {
                code: 'op_efield_fail_employee',
                name: 'Ключевой сотрудник против',
            },
            { code: 'op_efield_fail_off', name: 'Не хотят общаться' },
            {
                code: 'op_efield_fail_off',
                name: 'Не хотят общаться',
            },
            // {
            //     code: 'op_efield_fail_offasdasdsadasdasdsad',
            //     name: 'asdsadasdasdasdasd',
            // },
            // {
            //     code: 'op_efield_fail_offasdasdsadaasdasdsadsdasdd',
            //     name: 'фывыфвыфвфывфыв',
            // },
        ],
        code: 'op_efield_fail_reason',
        lead: 'OP_EFIELD_FAIL_REASON',
        company: 'OP_EFIELD_FAIL_REASON',
        deal: 'OP_EFIELD_FAIL_REASON',
        smart: '',
        task: '',
        app: 'calling',
        order: 230,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП Комментарии после отказов',
        appType: 'fail',
        type: 'multiple',
        items: [],
        code: 'op_fail_comments',
        lead: 'OP_FAIL_COMMENTS',
        company: 'OP_FAIL_COMMENTS',
        deal: 'OP_FAIL_COMMENTS',
        smart: '',
        task: '',
        app: 'calling',
        order: 230,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП Причины нерезультативности',
        appType: 'noresult',
        type: 'enumeration',
        items: [
            { code: 'secretar', name: 'Секретарь' },
            { code: 'nopickup', name: 'Недозвон - трубку не берут' },
            { code: 'nonumber', name: 'Недозвон - номер не существует' },
            { code: 'busy', name: 'Занято' },
            { code: 'notime', name: 'Перенос - не было времени' },
            { code: 'nocontact', name: 'Контактера нет на месте' },
            { code: 'giveup', name: 'Просят оставить свой номер' },
            { code: 'bay', name: 'Не интересует, до свидания' },
            { code: 'wrong', name: 'По телефону отвечает не та организация' },
            { code: 'auto', name: 'Автоответчик' },
        ],
        code: 'op_noresult_reason',
        lead: 'OP_NORESULT_REASON',
        company: 'OP_NORESULT_REASON',
        deal: 'OP_NORESULT_REASON',
        smart: '',
        task: '',
        app: 'calling',
        order: 230,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП Статус Клиента',
        appType: 'general',
        type: 'enumeration',
        items: [
            { code: 'free', name: 'Свободен' },
            { code: 'chok', name: 'ЧОК' },
            { code: 'nok', name: 'НОК' },
            { code: 'ok', name: 'ОК' },
            { code: 'stranger_kup', name: 'Чужой КУП' },
            { code: 'stranger_kupkk', name: 'Чужой КУП КК' },
            { code: 'stranger_kgurp', name: 'Чужой КГУ РП' },
            { code: 'own_kup', name: 'Свой КУП' },
            { code: 'own_kupkk', name: 'Свой КУП КК' },
            { code: 'own_kgurp', name: 'Свой КГУ РП' },
        ],
        code: 'op_client_status',
        lead: 'OP_CLIENT_STATUS',
        company: 'OP_CLIENT_STATUS',
        deal: 'OP_CLIENT_STATUS',
        smart: '',
        task: '',
        app: 'calling',
        order: 230,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП Пргноз работы',
        appType: 'general',
        type: 'enumeration',
        items: [
            { code: 'red', name: 'Красный' },
            { code: 'yellow', name: 'Желтый' },
            { code: 'green', name: 'Зеленый' },
        ],
        code: 'op_prospects',
        lead: 'OP_PROSPECTS',
        company: 'OP_PROSPECTS',
        deal: 'OP_PROSPECTS',
        smart: '',
        task: '',
        app: 'calling',
        order: 230,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Тип Клиента',
        appType: 'general',
        type: 'enumeration',
        items: [
            { code: 'state', name: 'Бюджетники' },
            { code: 'commerc', name: 'Коммерческие' },
            { code: 'ip', name: 'ИП' },
            { code: 'fiz', name: 'Физ лицо' },
            { code: 'layer', name: 'Адвокаты' },
        ],
        code: 'op_client_type',
        lead: 'OP_CLIENT_TYPE',
        company: 'OP_CLIENT_TYPE',
        deal: 'OP_CLIENT_TYPE',
        smart: '',
        task: '',
        app: 'calling',
        order: 230,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Конкуренты',
        appType: 'general',
        type: 'enumeration',
        items: [
            { code: 'kons_plus', name: 'Консультант+' },
            { code: 'action', name: 'Актион' },
            { code: 'kodex', name: 'Кодекс' },
            { code: 'bitrix', name: '1С' },
            { code: 'kontur', name: 'Контур' },
            { code: 'internet', name: 'Интернет' },
            { code: 'magazine', name: 'Журналы' },
        ],
        code: 'op_concurents',
        lead: 'OP_CONCURENTS',
        company: 'OP_CONCURENTS',
        deal: 'OP_CONCURENTS',
        smart: '',
        task: '',
        app: 'calling',
        order: 230,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Конкуренты',
        appType: 'general',
        type: 'enumeration',
        items: [
            { code: 'kons_plus', name: 'Консультант+' },
            { code: 'action', name: 'Актион' },
            { code: 'kodex', name: 'Кодекс' },
            { code: 'tech_expert', name: 'Техэксперт' },
            { code: 'kontur', name: 'Контур НОРМАТИВ' },
            { code: 'bitrix', name: '1С ИТС' },
            { code: 'my_business', name: 'Мое дело' },
            { code: 'case_look', name: 'CaseLook' },
            { code: 'audar_info', name: 'Аюдар-Инфо' },
            { code: 'internet', name: 'Интернет' },
            { code: 'magazine', name: 'Журналы' },
            { code: 'other', name: 'Другое' },
        ],
        code: 'op_concurents_multiple',
        lead: 'OP_CONCURENTS_MULTIPLE',
        company: 'OP_CONCURENTS_MULTIPLE',
        deal: 'OP_CONCURENTS_MULTIPLE',
        smart: '',
        task: '',
        app: 'calling',
        order: 230,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: true,
    },
    {
        name: 'Что известно о конкурентах',
        appType: 'general',
        type: 'enumeration',
        items: [
            {
                value: 'Отказались',
                del: 'N',
                xml_id: 'fail',
                code: 'fail',
                sort: 10,
            },
            {
                value: 'Обслуживаются',
                del: 'N',
                xml_id: 'success',
                code: 'success',
                sort: 20,
            },
            {
                value: 'Неизвестно',
                del: 'N',
                xml_id: 'xz',
                code: 'xz',
                sort: 30,
            },
        ] as const,
        code: 'supply_information',
        lead: 'SUPPLY_INFORMATION',
        company: 'SUPPLY_INFORMATION',
        deal: 'SUPPLY_INFORMATION',
        smart: '',
        task: '',
        app: 'calling',
        order: 230,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Категории',
        appType: 'general',
        type: 'enumeration',
        items: [
            { code: 'kkk', name: 'ККК' },
            { code: 'kk', name: 'КК' },
            { code: 'vip', name: 'VIP' },
            { code: 'k', name: 'К' },
            { code: 'c', name: 'С' },
            { code: 'm', name: 'М' },
        ],
        code: 'op_category',
        lead: 'OP_CATEGORY',
        company: 'OP_CATEGORY',
        deal: 'OP_CATEGORY',
        smart: '',
        task: '',
        app: 'calling',
        order: 230,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'companyId',
        appType: 'general',
        type: 'string',
        items: [],
        code: 'op_smart_company_id',
        lead: '',
        company: '',
        deal: 'OP_SMART_COMPANY_ID',
        smart: '',
        task: '',
        app: 'calling',
        order: 230,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'smartId',
        appType: 'general',
        type: 'string',
        items: [],
        code: 'op_smart_id',
        lead: 'OP_SMART_ID',
        company: 'OP_SMART_ID',
        deal: 'OP_SMART_ID',
        smart: '',
        task: '',
        app: 'calling',
        order: 230,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'lidId',
        appType: 'general',
        type: 'string',
        items: [],
        code: 'op_smart_lid',
        lead: 'OP_SMART_LID',
        company: 'OP_SMART_LID',
        deal: 'OP_SMART_LID',
        smart: '',
        task: '',
        app: 'calling',
        order: 230,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: "lidId's",
        appType: 'general',
        type: 'multiple',
        items: [],
        code: 'op_smart_lids',
        lead: 'OP_SMART_LIDS',
        company: 'OP_SMART_LIDS',
        deal: 'OP_SMART_LIDS',
        smart: '',
        task: '',
        app: 'calling',
        order: 230,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Сумма предложения',
        appType: 'only_deals',
        type: 'money',
        items: [],
        code: 'offer_sum',
        lead: 'OFFER_SUM',
        company: 'OFFER_SUM',
        deal: 'OFFER_SUM',
        smart: '',
        task: '',
        app: 'calling',
        order: 240,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Корневая сделка Продажи',
        appType: 'only_deals',
        type: 'crm',
        items: [],
        code: 'to_base_sales',
        lead: 'TO_BASE_SALES',
        company: 'TO_BASE_SALES',
        deal: 'TO_BASE_SALES',
        smart: 'TO_BASE_SALES',
        task: '',
        app: 'calling',
        order: 240,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Сделка ХО Продажи',
        appType: 'only_deals',
        type: 'crm',
        items: [],
        code: 'to_xo_sales',
        lead: 'TO_XO_SALES',
        company: 'TO_XO_SALES',
        deal: 'TO_XO_SALES',
        smart: '',
        task: '',
        app: 'calling',
        order: 240,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Сделка Презентации Продажи',
        appType: 'only_deals',
        type: 'crm',
        items: [],
        code: 'to_presentation_sales',
        lead: 'TO_PRESENTATION_SALES',
        company: 'TO_PRESENTATION_SALES',
        deal: 'TO_PRESENTATION_SALES',
        smart: '',
        task: '',
        app: 'calling',
        order: 240,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Корневая сделка ТМЦ',
        appType: 'only_deals',
        type: 'crm',
        items: [],
        code: 'to_base_tmc',
        lead: 'TO_BASE_TMC',
        company: 'TO_BASE_TMC',
        deal: 'TO_BASE_TMC',
        smart: '',
        task: '',
        app: 'calling',
        order: 240,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Сделка Презентации ТМЦ',
        appType: 'only_deals',
        type: 'crm',
        items: [],
        code: 'to_presentation_tmc',
        lead: 'TO_PRESENTATION_TMC',
        company: 'TO_PRESENTATION_TMC',
        deal: 'TO_PRESENTATION_TMC',
        smart: '',
        task: '',
        app: 'calling',
        order: 240,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Корневая сделка Сервис',
        appType: 'only_deals',
        type: 'crm',
        items: [],
        code: 'to_base_service',
        lead: 'TO_BASE_SERVICE',
        company: 'TO_BASE_SERVICE',
        deal: 'TO_BASE_SERVICE',
        smart: '',
        task: '',
        app: 'calling',
        order: 240,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП Текущий статус',
        appType: 'op_current_status',
        type: 'string',
        items: [],
        code: 'op_current_status',
        lead: 'OP_CURRENT_STATUS',
        company: 'OP_CURRENT_STATUS',
        deal: 'OP_CURRENT_STATUS',
        smart: '',
        task: '',
        app: 'calling',
        order: 230,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП Результат',
        appType: 'calling',
        type: 'enumeration',
        items: [
            {
                value: 'Гарант/ Запрет',
                del: 'N',
                xml_id: 'op_prospects_garant',
                code: 'op_prospects_garant',
                sort: 11,
            },
            {
                value: 'Должники',
                del: 'N',
                xml_id: 'op_result_debts',
                code: 'op_result_debts',
                sort: 12,
            },
            {
                value: 'Заявка',
                del: 'N',
                xml_id: 'op_result_init',
                code: 'op_result_init',
                sort: 13,
            },
            {
                value: 'Клиенты',
                del: 'N',
                xml_id: 'op_result_clients',
                code: 'op_result_clients',
                sort: 14,
            },
            {
                value: 'Конкурент',
                del: 'N',
                xml_id: 'op_result_concurents',
                code: 'op_result_concurents',
                sort: 15,
            },
            {
                value: 'Неверный контакт',
                del: 'N',
                xml_id: 'op_result_fake',
                code: 'op_result_fake',
                sort: 16,
            },
            {
                value: 'Нет финансирования',
                del: 'N',
                xml_id: 'op_result_nofinance',
                code: 'op_result_nofinance',
                sort: 17,
            },
            {
                value: 'Нет_ перспектив',
                del: 'N',
                xml_id: 'op_prospects_nopersp',
                code: 'op_prospects_nopersp',
                sort: 18,
            },
            {
                value: 'Новое',
                del: 'N',
                xml_id: 'op_result_new',
                code: 'op_result_new',
                sort: 19,
            },
            {
                value: 'Отказ',
                del: 'N',
                xml_id: 'op_prospects_fail',
                code: 'op_prospects_fail',
                sort: 20,
            },
            {
                value: 'Отключенные',
                del: 'N',
                xml_id: 'op_result_exclient',
                code: 'op_result_exclient',
                sort: 21,
            },
            {
                value: 'Переговоры',
                del: 'N',
                xml_id: 'op_result_warm',
                code: 'op_result_warm',
                sort: 22,
            },
            {
                value: 'Перенос',
                del: 'N',
                xml_id: 'op_result_pound',
                code: 'op_result_pound',
                sort: 23,
            },
            {
                value: 'Пересечение',
                del: 'N',
                xml_id: 'op_result_other_partner',
                code: 'op_result_other_partner',
                sort: 24,
            },
            {
                value: 'Покупает ГО',
                del: 'N',
                xml_id: 'op_prospects_go',
                code: 'op_prospects_go',
                sort: 25,
            },
            {
                value: 'Пользователи',
                del: 'N',
                xml_id: 'op_prospects_users',
                code: 'op_prospects_users',
                sort: 26,
            },
            {
                value: 'Потерявшиеся/Закрывшиеся',
                del: 'N',
                xml_id: 'op_prospects_company',
                code: 'op_prospects_company',
                sort: 27,
            },
            {
                value: 'Пред. договоренность',
                del: 'N',
                xml_id: 'op_result_prewarm',
                code: 'op_result_prewarm',
                sort: 28,
            },
            {
                value: 'Прозвон ТМЦ',
                del: 'N',
                xml_id: 'op_result_tmc',
                code: 'op_result_tmc',
                sort: 29,
            },
            {
                value: 'Секретарь не пропускает',
                del: 'N',
                xml_id: 'secretar',
                code: 'secretar',
                sort: 30,
            },
            {
                value: 'ТНО/ТПЗ',
                del: 'N',
                xml_id: 'op_result_tnotpz',
                code: 'op_result_tnotpz',
                sort: 31,
            },
            {
                value: 'чужая территория',
                del: 'N',
                xml_id: 'op_prospects_territory',
                code: 'op_prospects_territory',
                sort: 34,
            },
            {
                value: 'Шанс',
                del: 'N',
                xml_id: 'op_result_chance',
                code: 'op_result_chance',
                sort: 35,
            },
        ] as const,
        code: 'op_work_result',
        lead: 'OP_WORK_RESULT',
        company: 'OP_WORK_RESULT',
        deal: 'OP_WORK_RESULT',
        smart: '',
        task: '',
        app: 'calling',
        order: 700,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ОП Результат',
        appType: 'general',
        type: 'string',
        items: [],
        code: 'op_work_result_string',
        lead: 'OP_WORK_RESULT_STRING',
        company: 'OP_WORK_RESULT_STRING',
        deal: 'OP_WORK_RESULT_STRING',
        smart: '',
        task: '',
        app: 'calling',
        order: 700,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Отдел',
        appType: 'calling',
        type: 'enumeration',
        items: [
            {
                value: 'ТМЦ',
                del: 'N',
                xml_id: 'dep_tmc',
                code: 'dep_tmc',
                sort: 10,
            },
            {
                value: 'Отдел продаж',
                del: 'N',
                xml_id: 'dep_sales',
                code: 'dep_sales',
                sort: 20,
            },
            {
                value: 'Отдел Сервиса',
                del: 'N',
                xml_id: 'dep_service',
                code: 'dep_service',
                sort: 30,
            },
            {
                value: 'Буфер',
                del: 'N',
                xml_id: 'dep_buffer',
                code: 'dep_buffer',
                sort: 40,
            },
        ] as const,
        code: 'department',
        lead: 'DEPARTMENT',
        company: 'DEPARTMENT',
        deal: 'DEPARTMENT',
        smart: '',
        task: '',
        app: 'calling',
        order: 701,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Источник',
        appType: 'calling',
        type: 'string',
        items: [],
        code: 'client_source',
        lead: 'CLIENT_SOURCE',
        company: 'CLIENT_SOURCE',
        deal: 'CLIENT_SOURCE',
        smart: '',
        task: '',
        app: 'calling',
        order: 702,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Источник список',
        appType: 'calling',
        type: 'enumeration',
        items: [
            {
                value: 'Заявка с сайта',
                del: 'N',
                xml_id: 'op_source_1',
                code: 'op_source_1',
                sort: 10,
            },
            {
                value: 'Интернет',
                del: 'N',
                xml_id: 'op_source_2',
                code: 'op_source_2',
                sort: 20,
            },
            {
                value: '2ГИС',
                del: 'N',
                xml_id: 'op_source_3',
                code: 'op_source_3',
                sort: 30,
            },
            {
                value: 'Сайт закупки',
                del: 'N',
                xml_id: 'op_source_4',
                code: 'op_source_4',
                sort: 40,
            },
            {
                value: 'Восстановление',
                del: 'N',
                xml_id: 'op_source_5',
                code: 'op_source_5',
                sort: 50,
            },
            {
                value: 'Платная база',
                del: 'N',
                xml_id: 'op_source_6',
                code: 'op_source_6',
                sort: 60,
            },
            {
                value: 'Семинар',
                del: 'N',
                xml_id: 'op_source_7',
                code: 'op_source_7',
                sort: 70,
            },
        ] as const,
        code: 'op_source_select',
        lead: 'OP_SOURCE_SELECT',
        company: 'OP_SOURCE_SELECT',
        deal: 'OP_SOURCE_SELECT',
        smart: '',
        task: '',
        app: 'calling',
        order: 703,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Конкуренты договор до',
        appType: 'calling',
        type: 'date',
        items: [],
        code: 'op_concurent_contract_date',
        lead: 'OP_CONCURENT_CONTRACT_DATE',
        company: 'OP_CONCURENT_CONTRACT_DATE',
        deal: 'OP_CONCURENT_CONTRACT_DATE',
        smart: '',
        task: '',
        app: 'calling',
        order: 703,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Конкуренты оплачено до',
        appType: 'calling',
        type: 'date',
        items: [],
        code: 'op_concurent_pay_date',
        lead: 'OP_CONCURENT_PAY_DATE',
        company: 'OP_CONCURENT_PAY_DATE',
        deal: 'OP_CONCURENT_PAY_DATE',
        smart: '',
        task: '',
        app: 'calling',
        order: 703,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
] as const;

export type PbxSalesEventField = (typeof PBX_SALES_EVENT_FIELDS)[number];
export type PbxSalesEventFieldCode = PbxSalesEventField['code'];

/** Finds a field by `code` with a narrowed literal type (including `items`). */
export function findPbxSalesEventField<const C extends PbxSalesEventFieldCode>(
    code: C,
): Extract<PbxSalesEventField, { code: C }> | undefined {
    return PBX_SALES_EVENT_FIELDS.find(
        (field): field is Extract<PbxSalesEventField, { code: C }> =>
            field.code === code,
    );
}

export type PbxSalesEventFieldType = PbxSalesEventField['type'];
export type PbxSalesEventFieldAppType = PbxSalesEventField['appType'];
export type PbxSalesEventFieldApp = PbxSalesEventField['app'];

export type PbxSalesEventFieldWithItems = FieldWithItems<
    typeof PBX_SALES_EVENT_FIELDS,
    'items'
>;
export type PbxSalesEventFieldWithItemsCode =
    PbxSalesEventFieldWithItems['code'];
export type PbxSalesEventFieldItemCode<
    Code extends PbxSalesEventFieldWithItemsCode,
> = FieldItemCode<typeof PBX_SALES_EVENT_FIELDS, 'items', Code>;
export type PbxSalesEventFieldItemCodesMap = FieldItemCodesMap<
    typeof PBX_SALES_EVENT_FIELDS,
    'items'
>;

export const PBX_SALES_EVENT_FIELD_CODES = Object.freeze(
    createEnumObject(
        PBX_SALES_EVENT_FIELDS.map(
            field => field.code,
        ) as readonly PbxSalesEventFieldCode[],
    ),
);

export const PBX_SALES_EVENT_FIELD_TYPES = Object.freeze(
    createEnumObject(
        PBX_SALES_EVENT_FIELDS.map(
            field => field.type,
        ) as readonly PbxSalesEventFieldType[],
    ),
);

export const PBX_SALES_EVENT_FIELD_APP_TYPES = Object.freeze(
    createEnumObject(
        PBX_SALES_EVENT_FIELDS.map(
            field => field.appType,
        ) as readonly PbxSalesEventFieldAppType[],
    ),
);

export const PBX_SALES_EVENT_FIELD_APPS = Object.freeze(
    createEnumObject(
        PBX_SALES_EVENT_FIELDS.map(
            field => field.app,
        ) as readonly PbxSalesEventFieldApp[],
    ),
);

export const PBX_SALES_EVENT_FIELD_ITEM_CODES = Object.freeze(
    createFieldItemsEnum(PBX_SALES_EVENT_FIELDS, 'items'),
);
