import { createEnumObject, createFieldItemsEnum, FieldItemCode, FieldItemCodesMap, FieldWithItems } from "../../field/type/pbx-field-type.util";

export const PBX_SALES_KPI_LIST_FIELDS = [
    {
        type: 'datetime',
        appType: 'calling',
        name: 'Дата',
        title: 'Дата',
        bitrixId: 'EVENT_DATE',
        code: 'event_date',
        isActive: true,
        isNeedUpdate: true,
        order: 10,
        items: [],
    },
    {
        type: 'string',
        appType: 'calling',
        name: 'Название',
        title: 'Название',
        bitrixId: 'EVENT_TITLE',
        code: 'event_title',
        isActive: true,
        isNeedUpdate: true,
        order: 20,
        items: [],
    },
    {
        type: 'datetime',
        appType: 'calling',
        name: 'Дата следующей коммуникации',
        title: 'Дата следующей коммуникации',
        bitrixId: 'PLAN_DATE',
        code: 'plan_date',
        isActive: true,
        isNeedUpdate: true,
        order: 30,
        items: [],
    },
    {
        type: 'employee',
        appType: 'calling',
        name: 'Автор',
        title: 'Автор',
        bitrixId: 'AUTHOR',
        code: 'author',
        isActive: true,
        isNeedUpdate: true,
        order: 40,
        items: [],
    },
    {
        type: 'employee',
        appType: 'calling',
        name: 'Ответственный',
        title: 'Ответственный',
        bitrixId: 'RESPONSIBLE',
        code: 'responsible',
        isActive: true,
        isNeedUpdate: true,
        order: 50,
        items: [],
    },
    {
        type: 'employee',
        appType: 'calling',
        name: 'Соисполнитель',
        title: 'Соисполнитель',
        bitrixId: 'SU',
        code: 'su',
        isActive: true,
        isNeedUpdate: true,
        order: 60,
        items: [],
    },
    {
        type: 'crm',
        appType: 'calling',
        name: 'CRM',
        title: 'CRM',
        bitrixId: 'CRM',
        code: 'crm',
        isActive: true,
        isNeedUpdate: true,
        order: 70,
        items: [],
    },
    {
        type: 'string',
        appType: 'calling',
        name: 'Комментарий',
        title: 'Комментарий',
        bitrixId: 'MANAGER_COMMENT',
        code: 'manager_comment',
        isActive: true,
        isNeedUpdate: true,
        order: 80,
        items: [],
    },
    {
        type: 'enumeration',
        appType: 'calling',
        name: 'Тип События',
        title: 'Тип События',
        bitrixId: 'EVENT_TYPE',
        code: 'event_type',
        isActive: true,
        isNeedUpdate: true,
        order: 90,
        items: [
            {
                bitrixCode: 'XO',
                code: 'xo',
                fieldCode: 'event_type',
                isActive: true,
                isNeedUpdate: true,
                name: 'Холодный звонок',
                SORT: 10,
                VALUE: 'Холодный звонок',
            },
            {
                bitrixCode: 'CALL',
                code: 'call',
                fieldCode: 'event_type',
                isActive: true,
                isNeedUpdate: true,
                name: 'Звонок',
                SORT: 20,
                VALUE: 'Звонок',
            },
            {
                bitrixCode: 'PRESENTATION',
                code: 'presentation',
                fieldCode: 'event_type',
                isActive: true,
                isNeedUpdate: true,
                name: 'Презентация',
                SORT: 30,
                VALUE: 'Презентация',
            },
            {
                bitrixCode: 'INFO',
                code: 'info',
                fieldCode: 'event_type',
                isActive: true,
                isNeedUpdate: true,
                name: 'Информация',
                SORT: 40,
                VALUE: 'Информация',
            },
            {
                bitrixCode: 'SEMINAR',
                code: 'seminar',
                fieldCode: 'event_type',
                isActive: true,
                isNeedUpdate: true,
                name: 'Приглашение на семинар',
                SORT: 50,
                VALUE: 'Приглашение на семинар',
            },
            {
                bitrixCode: 'CALL_IN_PROGRESS',
                code: 'call_in_progress',
                fieldCode: 'event_type',
                isActive: true,
                isNeedUpdate: true,
                name: 'Звонок по решению',
                SORT: 60,
                VALUE: 'Звонок по решению',
            },
            {
                bitrixCode: 'CALL_IN_MONEY',
                code: 'call_in_money',
                fieldCode: 'event_type',
                isActive: true,
                isNeedUpdate: true,
                name: 'Звонок по оплате',
                SORT: 70,
                VALUE: 'Звонок по оплате',
            },
            {
                bitrixCode: 'COME_CALL',
                code: 'come_call',
                fieldCode: 'event_type',
                isActive: true,
                isNeedUpdate: true,
                name: 'Входящий звонок',
                SORT: 80,
                VALUE: 'Входящий звонок',
            },
            {
                bitrixCode: 'SITE',
                code: 'site',
                fieldCode: 'event_type',
                isActive: true,
                isNeedUpdate: true,
                name: 'Заявка с сайта',
                SORT: 90,
                VALUE: 'Заявка с сайта',
            },
        ],
    },
    {
        type: 'enumeration',
        appType: 'calling',
        name: 'Событие',
        title: 'Событие',
        bitrixId: 'EVENT_ACTION',
        code: 'event_action',
        isActive: true,
        isNeedUpdate: true,
        order: 100,
        items: [
            {
                bitrixCode: 'PLAN',
                code: 'plan',
                fieldCode: 'event_action',
                isActive: true,
                isNeedUpdate: true,
                name: 'Запланирован',
                SORT: 10,
                VALUE: 'Запланирован',
            },
            {
                bitrixCode: 'EXPIRED',
                code: 'expired',
                fieldCode: 'event_action',
                isActive: true,
                isNeedUpdate: true,
                name: 'Просрочен',
                SORT: 20,
                VALUE: 'Просрочен',
            },
            {
                bitrixCode: 'DONE',
                code: 'done',
                fieldCode: 'event_action',
                isActive: true,
                isNeedUpdate: true,
                name: 'Состоялся',
                SORT: 30,
                VALUE: 'Состоялся',
            },
            {
                bitrixCode: 'POUND',
                code: 'pound',
                fieldCode: 'event_action',
                isActive: true,
                isNeedUpdate: true,
                name: 'Перенос',
                SORT: 50,
                VALUE: 'Перенос',
            },
        ],
    },
    {
        type: 'enumeration',
        appType: 'calling',
        name: 'Результативность',
        title: 'Результативность',
        bitrixId: 'OP_RESULT_STATUS',
        code: 'op_result_status',
        isActive: true,
        isNeedUpdate: true,
        order: 110,
        items: [
            {
                bitrixCode: 'OP_CALL_RESULT_YES',
                code: 'op_call_result_yes',
                fieldCode: 'op_result_status',
                isActive: true,
                isNeedUpdate: true,
                name: 'Да',
                SORT: 10,
                VALUE: 'Да',
            },
            {
                bitrixCode: 'OP_CALL_RESULT_NO',
                code: 'op_call_result_no',
                fieldCode: 'op_result_status',
                isActive: true,
                isNeedUpdate: true,
                name: 'Нет',
                SORT: 20,
                VALUE: 'Нет',
            },
        ],
    },
    {
        type: 'enumeration',
        appType: 'calling',
        name: 'Тип Нерезультативности',
        title: 'Тип Нерезультативности',
        bitrixId: 'OP_NORESULT_REASON',
        code: 'op_noresult_reason',
        isActive: true,
        isNeedUpdate: true,
        order: 120,
        items: [
            {
                bitrixCode: 'SECRETAR',
                code: 'secretar',
                fieldCode: 'op_noresult_reason',
                isActive: true,
                isNeedUpdate: true,
                name: 'Секретарь',
                SORT: 10,
                VALUE: 'Секретарь',
            },
            {
                bitrixCode: 'NOPICKUP',
                code: 'nopickup',
                fieldCode: 'op_noresult_reason',
                isActive: true,
                isNeedUpdate: true,
                name: 'Недозвон - трубку не берут',
                SORT: 20,
                VALUE: 'Недозвон - трубку не берут',
            },
            {
                bitrixCode: 'NONUMBER',
                code: 'nonumber',
                fieldCode: 'op_noresult_reason',
                isActive: true,
                isNeedUpdate: true,
                name: 'Недозвон - номер не существует',
                SORT: 30,
                VALUE: 'Недозвон - номер не существует',
            },
            {
                bitrixCode: 'BUSY',
                code: 'busy',
                fieldCode: 'op_noresult_reason',
                isActive: true,
                isNeedUpdate: true,
                name: 'Занято',
                SORT: 40,
                VALUE: 'Занято',
            },
            {
                bitrixCode: 'NORESULT_NOTIME',
                code: 'noresult_notime',
                fieldCode: 'op_noresult_reason',
                isActive: true,
                isNeedUpdate: true,
                name: 'Перенос - не было времени',
                SORT: 50,
                VALUE: 'Перенос - не было времени',
            },
            {
                bitrixCode: 'NOCONTACT',
                code: 'nocontact',
                fieldCode: 'op_noresult_reason',
                isActive: true,
                isNeedUpdate: true,
                name: 'Контактера нет на месте',
                SORT: 60,
                VALUE: 'Контактера нет на месте',
            },
            {
                bitrixCode: 'GIVEUP',
                code: 'giveup',
                fieldCode: 'op_noresult_reason',
                isActive: true,
                isNeedUpdate: true,
                name: 'Просят оставить свой номер',
                SORT: 70,
                VALUE: 'Просят оставить свой номер',
            },
            {
                bitrixCode: 'BAY',
                code: 'bay',
                fieldCode: 'op_noresult_reason',
                isActive: true,
                isNeedUpdate: true,
                name: 'Не интересует, до свидания',
                SORT: 80,
                VALUE: 'Не интересует, до свидания',
            },
            {
                bitrixCode: 'WRONG',
                code: 'wrong',
                fieldCode: 'op_noresult_reason',
                isActive: true,
                isNeedUpdate: true,
                name: 'По телефону отвечает не та организация',
                SORT: 90,
                VALUE: 'По телефону отвечает не та организация',
            },
            {
                bitrixCode: 'AUTO',
                code: 'auto',
                fieldCode: 'op_noresult_reason',
                isActive: true,
                isNeedUpdate: true,
                name: 'Автоответчик',
                SORT: 100,
                VALUE: 'Автоответчик',
            },
        ],
    },
    {
        type: 'enumeration',
        appType: 'calling',
        name: 'Статус Работы',
        title: 'Статус Работы',
        bitrixId: 'OP_WORK_STATUS',
        code: 'op_work_status',
        isActive: true,
        isNeedUpdate: true,
        order: 130,
        items: [
            {
                bitrixCode: 'OP_STATUS_IN_WORK',
                code: 'op_status_in_work',
                fieldCode: 'op_work_status',
                isActive: true,
                isNeedUpdate: true,
                name: 'В работе',
                SORT: 10,
                VALUE: 'В работе',
            },
            {
                bitrixCode: 'OP_STATUS_IN_LONG',
                code: 'op_status_in_long',
                fieldCode: 'op_work_status',
                isActive: true,
                isNeedUpdate: true,
                name: 'На долгий период',
                SORT: 20,
                VALUE: 'На долгий период',
            },
            {
                bitrixCode: 'OP_STATUS_SUCCESS',
                code: 'op_status_success',
                fieldCode: 'op_work_status',
                isActive: true,
                isNeedUpdate: true,
                name: 'Продажа',
                SORT: 30,
                VALUE: 'Продажа',
            },
            {
                bitrixCode: 'OP_STATUS_IN_PROGRESS',
                code: 'op_status_in_progress',
                fieldCode: 'op_work_status',
                isActive: true,
                isNeedUpdate: true,
                name: 'В решении',
                SORT: 40,
                VALUE: 'В решении',
            },
            {
                bitrixCode: 'OP_STATUS_MONEY_AWAIT',
                code: 'op_status_money_await',
                fieldCode: 'op_work_status',
                isActive: true,
                isNeedUpdate: true,
                name: 'В оплате',
                SORT: 50,
                VALUE: 'В оплате',
            },
            {
                bitrixCode: 'OP_STATUS_FAIL',
                code: 'op_status_fail',
                fieldCode: 'op_work_status',
                isActive: true,
                isNeedUpdate: true,
                name: 'Отказ',
                SORT: 60,
                VALUE: 'Отказ',
            },
        ],
    },
    {
        type: 'enumeration',
        appType: 'calling',
        name: 'Неперспективная',
        title: 'Неперспективная',
        bitrixId: 'OP_FAIL_TYPE',
        code: 'op_fail_type',
        isActive: true,
        isNeedUpdate: true,
        order: 140,
        items: [
            {
                bitrixCode: 'GARANT',
                code: 'garant',
                fieldCode: 'op_fail_type',
                isActive: true,
                isNeedUpdate: true,
                name: 'Гарант/Запрет',
                SORT: 10,
                VALUE: 'Гарант/Запрет',
            },
            {
                bitrixCode: 'NO_PERSPECT',
                code: 'no_perspect',
                fieldCode: 'op_fail_type',
                isActive: true,
                isNeedUpdate: true,
                name: 'Нет перспектив',
                SORT: 20,
                VALUE: 'Нет перспектив',
            },
            {
                bitrixCode: 'GO',
                code: 'go',
                fieldCode: 'op_fail_type',
                isActive: true,
                isNeedUpdate: true,
                name: 'Покупает ГО',
                SORT: 30,
                VALUE: 'Покупает ГО',
            },
            {
                bitrixCode: 'TERRITORY',
                code: 'territory',
                fieldCode: 'op_fail_type',
                isActive: true,
                isNeedUpdate: true,
                name: 'Чужая территория',
                SORT: 40,
                VALUE: 'Чужая территория',
            },
            {
                bitrixCode: 'ACCOUNTANT',
                code: 'accountant',
                fieldCode: 'op_fail_type',
                isActive: true,
                isNeedUpdate: true,
                name: 'Бухприх',
                SORT: 50,
                VALUE: 'Бухприх',
            },
            {
                bitrixCode: 'AUTSORC',
                code: 'autsorc',
                fieldCode: 'op_fail_type',
                isActive: true,
                isNeedUpdate: true,
                name: 'Аутсорсинг',
                SORT: 60,
                VALUE: 'Аутсорсинг',
            },
            {
                bitrixCode: 'DEPEND',
                code: 'depend',
                fieldCode: 'op_fail_type',
                isActive: true,
                isNeedUpdate: true,
                name: 'Несамостоятельная организация',
                SORT: 70,
                VALUE: 'Несамостоятельная организация',
            },
            {
                bitrixCode: 'FAILURE',
                code: 'failure',
                fieldCode: 'op_fail_type',
                isActive: true,
                isNeedUpdate: true,
                name: 'Отказ',
                SORT: 80,
                VALUE: 'Отказ',
            },
            {
                bitrixCode: 'NOFAILURE',
                code: 'nofailure',
                fieldCode: 'op_fail_type',
                isActive: true,
                isNeedUpdate: true,
                name: 'Перспективная',
                SORT: 90,
                VALUE: 'Перспективная',
            },
        ],
    },
    {
        type: 'enumeration',
        appType: 'calling',
        name: 'ОП Причина Отказа',
        title: 'ОП Причина Отказа',
        bitrixId: 'OP_FAIL_REASON',
        code: 'op_fail_reason',
        isActive: true,
        isNeedUpdate: true,
        order: 150,
        items: [
            {
                bitrixCode: 'FAIL_NOTIME',
                code: 'fail_notime',
                fieldCode: 'op_fail_reason',
                isActive: true,
                isNeedUpdate: true,
                name: 'не было времени',
                SORT: 10,
                VALUE: 'не было времени',
            },
            {
                bitrixCode: 'C_HABIT',
                code: 'c_habit',
                fieldCode: 'op_fail_reason',
                isActive: true,
                isNeedUpdate: true,
                name: 'конкуренты - привыкли',
                SORT: 20,
                VALUE: 'конкуренты - привыкли',
            },
            {
                bitrixCode: 'C_PREPAY',
                code: 'c_prepay',
                fieldCode: 'op_fail_reason',
                isActive: true,
                isNeedUpdate: true,
                name: 'конкуренты - оплачено',
                SORT: 30,
                VALUE: 'конкуренты - оплачено',
            },
            {
                bitrixCode: 'C_PRICE',
                code: 'c_price',
                fieldCode: 'op_fail_reason',
                isActive: true,
                isNeedUpdate: true,
                name: 'конкуренты - цена',
                SORT: 40,
                VALUE: 'конкуренты - цена',
            },
            {
                bitrixCode: 'TO_EXPENSIVE',
                code: 'to_expensive',
                fieldCode: 'op_fail_reason',
                isActive: true,
                isNeedUpdate: true,
                name: 'слишком дорого',
                SORT: 50,
                VALUE: 'слишком дорого',
            },
            {
                bitrixCode: 'TO_CHEAP',
                code: 'to_cheap',
                fieldCode: 'op_fail_reason',
                isActive: true,
                isNeedUpdate: true,
                name: 'слишком дешево',
                SORT: 60,
                VALUE: 'слишком дешево',
            },
            {
                bitrixCode: 'NOMONEY',
                code: 'nomoney',
                fieldCode: 'op_fail_reason',
                isActive: true,
                isNeedUpdate: true,
                name: 'нет денег',
                SORT: 70,
                VALUE: 'нет денег',
            },
            {
                bitrixCode: 'NONEED',
                code: 'noneed',
                fieldCode: 'op_fail_reason',
                isActive: true,
                isNeedUpdate: true,
                name: 'не видят надобности',
                SORT: 80,
                VALUE: 'не видят надобности',
            },
            {
                bitrixCode: 'LPR',
                code: 'lpr',
                fieldCode: 'op_fail_reason',
                isActive: true,
                isNeedUpdate: true,
                name: 'лпр против',
                SORT: 90,
                VALUE: 'лпр против',
            },
            {
                bitrixCode: 'EMPLOYEE',
                code: 'employee',
                fieldCode: 'op_fail_reason',
                isActive: true,
                isNeedUpdate: true,
                name: 'ключевой сотрудник против',
                SORT: 100,
                VALUE: 'ключевой сотрудник против',
            },
        ],
    },
] as const;

export const PBX_SALES_KPI_LISTS = [
    {
        type: 'kpi',
        group: 'sales',
        name: 'KPI',
        title: 'ОП KPI',
        bitrixId: '',
        bitrixCamelId: '',
        code: 'kpi',
        isActive: true,
        order: 1,
        isNeedUpdate: true,
        fields: PBX_SALES_KPI_LIST_FIELDS,
    },
    {
        type: 'kpi',
        group: 'sales',
        name: 'history',
        title: 'ОП История работы',
        bitrixId: '',
        bitrixCamelId: '',
        code: 'history',
        isActive: true,
        order: 2,
        isNeedUpdate: true,
        fields: PBX_SALES_KPI_LIST_FIELDS,
    },
] as const;

export type PbxSalesKpiList = (typeof PBX_SALES_KPI_LISTS)[number];
export type PbxSalesKpiListCode = PbxSalesKpiList['code'];
export type PbxSalesKpiListType = PbxSalesKpiList['type'];
export type PbxSalesKpiListGroup = PbxSalesKpiList['group'];

export type PbxSalesKpiListField = (typeof PBX_SALES_KPI_LIST_FIELDS)[number];
export type PbxSalesKpiListFieldCode = PbxSalesKpiListField['code'];
export type PbxSalesKpiListFieldType = PbxSalesKpiListField['type'];
export type PbxSalesKpiListFieldAppType = PbxSalesKpiListField['appType'];
export type PbxSalesKpiListFieldBitrixId = PbxSalesKpiListField['bitrixId'];

export function findPbxSalesKpiList<const C extends PbxSalesKpiListCode>(
    code: C,
): Extract<PbxSalesKpiList, { code: C }> | undefined {
    return PBX_SALES_KPI_LISTS.find(
        (list): list is Extract<PbxSalesKpiList, { code: C }> =>
            list.code === code,
    );
}

export function findPbxSalesKpiListField<
    const C extends PbxSalesKpiListFieldCode,
>(code: C): Extract<PbxSalesKpiListField, { code: C }> | undefined {
    return PBX_SALES_KPI_LIST_FIELDS.find(
        (field): field is Extract<PbxSalesKpiListField, { code: C }> =>
            field.code === code,
    );
}

export type PbxSalesKpiListFieldWithItems = FieldWithItems<
    typeof PBX_SALES_KPI_LIST_FIELDS,
    'items'
>;
export type PbxSalesKpiListFieldWithItemsCode =
    PbxSalesKpiListFieldWithItems['code'];
export type PbxSalesKpiListFieldItemCode<
    Code extends PbxSalesKpiListFieldWithItemsCode,
> = FieldItemCode<typeof PBX_SALES_KPI_LIST_FIELDS, 'items', Code>;
export type PbxSalesKpiListFieldItemCodesMap = FieldItemCodesMap<
    typeof PBX_SALES_KPI_LIST_FIELDS,
    'items'
>;

export const PBX_SALES_KPI_LIST_CODES = Object.freeze(
    createEnumObject(
        PBX_SALES_KPI_LISTS.map(
            list => list.code,
        ) as readonly PbxSalesKpiListCode[],
    ),
);

export const PBX_SALES_KPI_LIST_FIELD_CODES = Object.freeze(
    createEnumObject(
        PBX_SALES_KPI_LIST_FIELDS.map(
            field => field.code,
        ) as readonly PbxSalesKpiListFieldCode[],
    ),
);

export const PBX_SALES_KPI_LIST_FIELD_TYPES = Object.freeze(
    createEnumObject(
        PBX_SALES_KPI_LIST_FIELDS.map(
            field => field.type,
        ) as readonly PbxSalesKpiListFieldType[],
    ),
);

export const PBX_SALES_KPI_LIST_FIELD_APP_TYPES = Object.freeze(
    createEnumObject(
        PBX_SALES_KPI_LIST_FIELDS.map(
            field => field.appType,
        ) as readonly PbxSalesKpiListFieldAppType[],
    ),
);

export const PBX_SALES_KPI_LIST_FIELD_BITRIX_IDS = Object.freeze(
    createEnumObject(
        PBX_SALES_KPI_LIST_FIELDS.map(
            field => field.bitrixId,
        ) as readonly PbxSalesKpiListFieldBitrixId[],
    ),
);

export const PBX_SALES_KPI_LIST_FIELD_ITEM_CODES = Object.freeze(
    createFieldItemsEnum(PBX_SALES_KPI_LIST_FIELDS, 'items'),
);
