import {
    createEnumObject,
    createFieldItemsEnum,
    FieldItemCode,
    FieldItemCodesMap,
    FieldWithItems,
} from '../../pbx-field-type.util';

export const PBX_SALES_KONSTRUCTOR_FIELDS = [
    {
        name: 'Наименование комплекта',
        appType: 'product',
        type: 'string',
        list: [],
        code: 'complect_name',
        lead: 'COMPLECT_NAME',
        company: 'COMPLECT_NAME',
        deal: 1684145200,
        smart: 'COMPLECT_NAME',
        order: 250,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'НПА',
        appType: 'update',
        type: 'multiple',
        list: [],
        code: 'npa',
        lead: '',
        company: '',
        deal: 1687967605,
        smart: '',
        order: 260,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Судебная практика',
        appType: 'update',
        type: 'multiple',
        list: [],
        code: 'la',
        lead: '',
        company: '',
        deal: 1687967766,
        smart: '',
        order: 260,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Консультационные материалы',
        appType: 'update',
        type: 'multiple',
        list: [],
        code: 'c',
        lead: '',
        company: '',
        deal: 1687967660,
        smart: '',
        order: 260,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Справочники',
        appType: 'update',
        type: 'multiple',
        list: [],
        code: 'sp',
        lead: '',
        company: '',
        deal: 1687967855,
        smart: '',
        order: 260,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ЭР',
        appType: 'update',
        type: 'multiple',
        list: [],
        code: 'er',
        lead: '',
        company: '',
        deal: 1687967828,
        smart: '',
        order: 260,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Пакет ЭР',
        appType: 'update',
        type: 'multiple',
        list: [],
        code: 'per',
        lead: '',
        company: '',
        deal: 1687967796,
        smart: '',
        order: 260,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ЭР в пакете',
        appType: 'update',
        type: 'multiple',
        list: [],
        code: 'erinpac',
        lead: '',
        company: '',
        deal: 1689144897,
        smart: '',
        order: 260,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Бесплатные блоки',
        appType: 'update',
        type: 'multiple',
        list: [],
        code: 'free_blocks',
        lead: '',
        company: '',
        deal: 1684145070,
        smart: '',
        order: 260,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Legal Tech',
        appType: 'update',
        type: 'multiple',
        list: [],
        code: 'lt',
        lead: '',
        company: '',
        deal: 1684145082,
        smart: '',
        order: 260,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Пакет LT',
        appType: 'update',
        type: 'multiple',
        list: [],
        code: 'plt',
        lead: '',
        company: '',
        deal: 1687967929,
        smart: '',
        order: 260,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'LT в пакете',
        appType: 'update',
        type: 'multiple',
        list: [],
        code: 'ltinpac',
        lead: '',
        company: '',
        deal: 1689145859,
        smart: '',
        order: 260,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Consalting',
        appType: 'update',
        type: 'multiple',
        list: [],
        code: 'consalting',
        lead: '',
        company: '',
        deal: 1684145094,
        smart: '',
        order: 260,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Вид поставки',
        appType: 'product',
        type: 'string',
        list: [],
        code: 'supply',
        lead: 'SUPPLY',
        company: 'SUPPLY',
        deal: 1687965585,
        smart: 'SUPPLY',
        order: 250,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Вид размещения',
        appType: 'product',
        type: 'string',
        list: [],
        code: 'supply_for_contract',
        lead: 'SUPPLY_FOR_CONTRACT',
        company: 'SUPPLY_FOR_CONTRACT',
        deal: 1687965613,
        smart: 'SUPPLY_FOR_CONTRACT',
        order: 250,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Примечание',
        appType: 'product',
        type: 'string',
        list: [],
        code: 'note',
        lead: '',
        company: '',
        deal: 1687965646,
        smart: '',
        order: 260,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Правовой Консалтинг',
        appType: 'product',
        type: 'string',
        list: [],
        code: 'consalting',
        lead: '',
        company: '',
        deal: 1687965767,
        smart: '',
        order: 260,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Примечание2',
        appType: 'product',
        type: 'string',
        list: [],
        code: 'note2',
        lead: '',
        company: '',
        deal: 1687965673,
        smart: '',
        order: 260,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Срок действия абон\\лиц',
        appType: 'product',
        type: 'string',
        list: [],
        code: 'abonement_time',
        lead: 'ABONEMENT_TIME',
        company: 'ABONEMENT_TIME',
        deal: 1687965902,
        smart: '',
        order: 250,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Носители, используемые при предоставлении услуг',
        appType: 'product',
        type: 'string',
        list: [],
        code: 'hdd',
        lead: '',
        company: '',
        deal: 1687965956,
        smart: '',
        order: 260,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Способ доставки носителя',
        appType: 'product',
        type: 'string',
        list: [],
        code: 'way',
        lead: '',
        company: '',
        deal: 1687966003,
        smart: '',
        order: 260,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Количество логин-паролей',
        appType: 'product',
        type: 'string',
        list: [],
        code: 'logins_quantity',
        lead: '',
        company: '',
        deal: 1687965791,
        smart: '',
        order: 260,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Количество логин-паролей(number)',
        appType: 'product',
        type: 'string',
        list: [],
        code: 'contract_supply_prop_q',
        lead: 'CONTRACT_SUPPLY_PROP_Q',
        company: 'CONTRACT_SUPPLY_PROP_Q',
        deal: 1689156336,
        smart: '',
        order: 250,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Примечание 3 - адрес электронной почты',
        appType: 'product',
        type: 'string',
        list: [],
        code: 'note_3',
        lead: '',
        company: '',
        deal: 1687965700,
        smart: '',
        order: 260,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Количество одновременных доступов',
        appType: 'product',
        type: 'string',
        list: [],
        code: 'offer_supply_q',
        lead: 'OFFER_SUPPLY_Q',
        company: 'OFFER_SUPPLY_Q',
        deal: 1689656448,
        smart: '',
        order: 260,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Количество КП',
        appType: 'statistics_op',
        type: 'integer',
        list: [],
        code: 'op_offer_q',
        lead: 'OP_OFFER_Q',
        company: 'OP_OFFER_Q',
        deal: 'OP_OFFER_Q',
        smart: 'OP_OFFER_Q',
        order: 270,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Количество Счетов',
        appType: 'statistics_op',
        type: 'integer',
        list: [],
        code: 'op_invoice_q',
        lead: 'OP_INVOICE_Q',
        company: 'OP_INVOICE_Q',
        deal: 'OP_INVOICE_Q',
        smart: 'OP_INVOICE_Q',
        order: 270,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Количество Договоров',
        appType: 'statistics_op',
        type: 'integer',
        list: [],
        code: 'op_contract_q',
        lead: 'OP_CONTRACT_Q',
        company: 'OP_CONTRACT_Q',
        deal: 'OP_CONTRACT_Q',
        smart: 'OP_CONTRACT_Q',
        order: 270,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Количество Поставок',
        appType: 'statistics_op',
        type: 'integer',
        list: [],
        code: 'op_supplies_q',
        lead: 'OP_SUPPLIES_Q',
        company: 'OP_SUPPLIES_Q',
        deal: 'OP_SUPPLIES_Q',
        smart: 'OP_SUPPLIES_Q',
        order: 270,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Количество КП после презентации',
        appType: 'statistics_op',
        type: 'integer',
        list: [],
        code: 'op_offer_pres_q',
        lead: 'OP_OFFER_PRES_Q',
        company: 'OP_OFFER_PRES_Q',
        deal: 'OP_OFFER_PRES_Q',
        smart: 'OP_OFFER_PRES_Q',
        order: 270,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Количество Счетов после презентации',
        appType: 'statistics_op',
        type: 'integer',
        list: [],
        code: 'op_invoice_pres_q',
        lead: 'OP_INVOICE_PRES_Q',
        company: 'OP_INVOICE_PRES_Q',
        deal: 'OP_INVOICE_PRES_Q',
        smart: 'OP_INVOICE_PRES_Q',
        order: 270,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'ИНН ',
        appType: 'document',
        type: 'string',
        list: [],
        code: 'op_inn',
        lead: 'OP_INN',
        company: 'OP_INN',
        deal: 'OP_INN',
        smart: 'OP_INN',
        order: 270,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Должность (для КП)',
        appType: 'document',
        type: 'string',
        list: [],
        code: 'op_position',
        lead: 'OP_POSITION',
        company: 'OP_POSITION',
        deal: 'OP_POSITION',
        smart: 'OP_POSITION',
        order: 270,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Имя Текущего контактного Лица',
        appType: 'document',
        type: 'string',
        list: [],
        code: 'op_name',
        lead: 'OP_NAME',
        company: 'OP_NAME',
        deal: 'OP_NAME',
        smart: 'OP_NAME',
        order: 270,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Контактные лица ',
        appType: 'document',
        type: 'multiple',
        list: [],
        code: 'op_contacts',
        lead: 'OP_CONTACTS',
        company: 'OP_CONTACTS',
        deal: 'OP_CONTACTS',
        smart: 'OP_CONTACTS',
        order: 270,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Дата отправки КП',
        appType: 'document',
        type: 'datetime',
        list: [],
        code: 'op_offer_date',
        lead: 'OP_OFFER_DATE',
        company: 'OP_OFFER_DATE',
        deal: 'OP_OFFER_DATE',
        smart: 'OP_OFFER_DATE',
        order: 270,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Дата отправки Счета',
        appType: 'document',
        type: 'datetime',
        list: [],
        code: 'op_invoice_date',
        lead: 'OP_INVOICE_DATE',
        company: 'OP_INVOICE_DATE',
        deal: 'OP_INVOICE_DATE',
        smart: 'OP_INVOICE_DATE',
        order: 270,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Дата отправки Договора',
        appType: 'document',
        type: 'datetime',
        list: [],
        code: 'op_contract_date',
        lead: 'OP_CONTRACT_DATE',
        company: 'OP_CONTRACT_DATE',
        deal: 'OP_CONTRACT_DATE',
        smart: 'OP_CONTRACT_DATE',
        order: 270,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Дейстивие договора с',
        appType: 'op_supply',
        type: 'date',
        list: [],
        code: 'contract_start',
        lead: 'CONTRACT_START',
        company: 'CONTRACT_START',
        deal: 'CONTRACT_START',
        smart: 'CONTRACT_START',
        order: 270,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Действие договора до',
        appType: 'op_supply',
        type: 'date',
        list: [],
        code: 'contract_end',
        lead: 'CONTRACT_END',
        company: 'CONTRACT_END',
        deal: 'CONTRACT_END',
        smart: 'CONTRACT_END',
        order: 270,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Дата первой оплаты',
        appType: 'op_supply',
        type: 'date',
        list: [],
        code: 'first_pay_date',
        lead: 'FIRST_PAY_DATE',
        company: 'FIRST_PAY_DATE',
        deal: 'FIRST_PAY_DATE',
        smart: 'FIRST_PAY_DATE',
        order: 280,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Срок истечения первого аванса',
        appType: 'op_supply',
        type: 'datetime',
        list: [],
        code: 'first_prepay_date',
        lead: 'FIRST_PREPAY_DATE',
        company: 'FIRST_PREPAY_DATE',
        deal: 'FIRST_PREPAY_DATE',
        smart: 'FIRST_PREPAY_DATE',
        order: 280,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Срок истечения второго аванса',
        appType: 'op_supply',
        type: 'datetime',
        list: [],
        code: 'second_prepay_date',
        lead: 'SECOND_PREPAY_DATE',
        company: 'SECOND_PREPAY_DATE',
        deal: 'SECOND_PREPAY_DATE',
        smart: 'SECOND_PREPAY_DATE',
        order: 280,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Срок истечения аванса',
        appType: 'op_supply',
        type: 'datetime',
        list: [],
        code: 'prepay_date',
        lead: 'PREPAY_DATE',
        company: 'PREPAY_DATE',
        deal: 'PREPAY_DATE',
        smart: 'PREPAY_DATE',
        order: 280,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Дата поставки',
        appType: 'op_supply',
        type: 'datetime',
        list: [],
        code: 'supply_date',
        lead: 'SUPPLY_DATE',
        company: 'SUPPLY_DATE',
        deal: 'SUPPLY_DATE',
        smart: 'SUPPLY_DATE',
        order: 280,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Дата первичного обучения',
        appType: 'op_supply',
        type: 'datetime',
        list: [],
        code: 'first_edu_date',
        lead: 'FIRST_EDU_DATE',
        company: 'FIRST_EDU_DATE',
        deal: 'FIRST_EDU_DATE',
        smart: 'FIRST_EDU_DATE',
        order: 280,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Комментарии к поставке',
        appType: 'op_supply',
        type: 'string',
        list: [],
        code: 'supply_comment',
        lead: 'SUPPLY_COMMENT',
        company: 'SUPPLY_COMMENT',
        deal: 'SUPPLY_COMMENT',
        smart: 'SUPPLY_COMMENT',
        order: 280,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Ответственный за получение справочника',
        appType: 'document',
        type: 'string',
        list: [],
        code: 'garant_client_assigned_name',
        lead: '',
        company: '',
        deal: 'GARANT_CLIENT_ASSIGNED_NAME',
        smart: 'GARANT_CLIENT_ASSIGNED_NAME',
        order: 300,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Номер телефона ответственного за получение справочника',
        appType: 'document',
        type: 'string',
        list: [],
        code: 'garant_client_assigned_phone',
        lead: '',
        company: '',
        deal: 'GARANT_CLIENT_ASSIGNED_PHONE',
        smart: 'GARANT_CLIENT_ASSIGNED_PHONE',
        order: 300,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Email телефона ответственного за получение справочника',
        appType: 'document',
        type: 'string',
        list: [],
        code: 'garant_client_assigned_email',
        lead: '',
        company: '',
        deal: 'GARANT_CLIENT_ASSIGNED_EMAIL',
        smart: 'GARANT_CLIENT_ASSIGNED_EMAIL',
        order: 300,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Email для интернет версии',
        appType: 'document',
        type: 'string',
        list: [],
        code: 'garant_client_email',
        lead: '',
        company: '',
        deal: 'GARANT_CLIENT_EMAIL',
        smart: 'GARANT_CLIENT_EMAIL',
        order: 300,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Дата договора договор от',
        appType: 'document',
        type: 'date',
        list: [],
        code: 'contract_create_date',
        lead: '',
        company: '',
        deal: 'CONTRACT_CREATE_DATE',
        smart: 'CONTRACT_CREATE_DATE',
        order: 300,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Период в подарок с',
        appType: 'document',
        type: 'date',
        list: [],
        code: 'contract_present_start',
        lead: '',
        company: '',
        deal: 'CONTRACT_PRESENT_START',
        smart: 'CONTRACT_PRESENT_START',
        order: 300,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Период в подарок по',
        appType: 'document',
        type: 'date',
        list: [],
        code: 'contract_present_end',
        lead: '',
        company: '',
        deal: 'CONTRACT_PRESENT_END',
        smart: 'CONTRACT_PRESENT_END',
        order: 300,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
    {
        name: 'Поставщик',
        appType: 'document',
        type: 'string',
        list: [],
        code: 'document_provider',
        lead: '',
        company: 'DOCUMENT_PROVIDER',
        deal: 'DOCUMENT_PROVIDER',
        smart: 'DOCUMENT_PROVIDER',
        order: 300,
        is_rewrite: '',
        isNeedUpdate: true,
        isMultiple: false,
    },
] as const;

export type PbxSalesKonstructorField =
    (typeof PBX_SALES_KONSTRUCTOR_FIELDS)[number];
export type PbxSalesKonstructorFieldCode = PbxSalesKonstructorField['code'];
export type PbxSalesKonstructorFieldType = PbxSalesKonstructorField['type'];
export type PbxSalesKonstructorFieldAppType =
    PbxSalesKonstructorField['appType'];

export type PbxSalesKonstructorFieldWithList = FieldWithItems<
    typeof PBX_SALES_KONSTRUCTOR_FIELDS,
    'list'
>;
export type PbxSalesKonstructorFieldWithListCode =
    PbxSalesKonstructorFieldWithList['code'];
export type PbxSalesKonstructorFieldListItemCode<
    Code extends PbxSalesKonstructorFieldWithListCode,
> = FieldItemCode<typeof PBX_SALES_KONSTRUCTOR_FIELDS, 'list', Code>;
export type PbxSalesKonstructorFieldListItemCodesMap = FieldItemCodesMap<
    typeof PBX_SALES_KONSTRUCTOR_FIELDS,
    'list'
>;

export const PBX_SALES_KONSTRUCTOR_FIELD_CODES = Object.freeze(
    createEnumObject(
        PBX_SALES_KONSTRUCTOR_FIELDS.map(
            field => field.code,
        ) as readonly PbxSalesKonstructorFieldCode[],
    ),
);

export const PBX_SALES_KONSTRUCTOR_FIELD_TYPES = Object.freeze(
    createEnumObject(
        PBX_SALES_KONSTRUCTOR_FIELDS.map(
            field => field.type,
        ) as readonly PbxSalesKonstructorFieldType[],
    ),
);

export const PBX_SALES_KONSTRUCTOR_FIELD_APP_TYPES = Object.freeze(
    createEnumObject(
        PBX_SALES_KONSTRUCTOR_FIELDS.map(
            field => field.appType,
        ) as readonly PbxSalesKonstructorFieldAppType[],
    ),
);

export const PBX_SALES_KONSTRUCTOR_FIELD_LIST_CODES = Object.freeze(
    createFieldItemsEnum(PBX_SALES_KONSTRUCTOR_FIELDS, 'list'),
);
