name: Deploy kpi-sales on push to main

on:
  push:
    branches:
      - main
    paths:
      - "apps/kpi-sales/**"  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ CI запущен
        run: echo "🚀 GitHub Actions запущен"

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          timeout: 30m
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "🧩 Подключение к серверу"
            cd /var/www/html/next/monorepo
            git pull origin main
            tmux kill-session -t kpi-sales-prod-deploy-session || true

            old_id=$(docker ps --filter "name=april-kpi-sales-prod" --format "{{.ID}}")

            tmux new -d -s kpi-sales-prod-deploy-session "\
            docker-compose --env-file .env build front-kpi-sales && \
            docker-compose --env-file .env up -d front-kpi-sales && \
            docker ps -a > /tmp/front-kpi-sales.log && \
            docker logs front-kpi-sales >> /tmp/front-kpi-sales.log && \
            echo ✅ Готово"

            echo "⏳ Жду, пока произойдёт обновление контейнера..."
            for i in {1..60}; do
              new_id=$(docker ps --filter "name=april-kpi-sales-prod" --format "{{.ID}}")
              if [ "$new_id" != "$old_id" ]; then
                echo "✅ Контейнер обновился: $old_id → $new_id"
                break
              fi
              docker ps -a
              echo "⌛ Контейнер ещё старый, жду..."
              sleep 15
            done




            echo "⌛ Ожидание запуска контейнера 60..."
            sleep 60
            

            docker ps -a
            docker logs april-kpi-sales-prod || true

