name: Deploy kpi-sales on push to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/html/next/kpi-sales
            git pull origin main
            pnpm install --frozen-lockfile
            pnpm turbo prune --filter=apps/kpi-sales --prune-dependency-graph
            cd out
            docker-compose up -d --build
