name: Deploy alfa on push to main

on:
  push:
    branches:
      - main
    paths:
      - "apps/alfa/**"  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ CI запущен
        run: echo "🚀 GitHub Actions запущен"

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          timeout: 30m
          script: |
            echo "🧩 Подключение к серверу"
            cd /var/www/html/next/monorepo
            git pull origin main
            tmux kill-session -t front-alfa-prod-deploy-session || true
            tmux new -d -s front-alfa-prod-deploy-session "\
            docker compose --env-file .env build front-alfa && \
            docker compose --env-file .env up -d front-alfa && \
            docker ps -a > /tmp/front-alfa.log && \
            docker logs front-alfa-prod >> /tmp/front-alfa.log && \
            echo ✅ Готово"


            echo "⌛ Ожидание запуска контейнера 60..."
            sleep 60
      
  
            docker ps -a
            docker logs front-alfa-prod || true

