name: Deploy konstructor on push to main

on:
  push:
    branches:
      - main
    paths:
      - "apps/konstructor/**"  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ CI запущен
        run: echo "🚀 GitHub Actions запущен"

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "🧩 Подключение к серверу"
            cd /var/www/html/next/monorepo
            git pull origin main
            tmux kill-session -t /front-konstructor-prod-deploy-session || true
            tmux new -d -s /front-konstructor-prod-deploy-session "\
            docker compose --env-file .env build front-konstructor && \
            docker compose --env-file .env up -d front-konstructor && \
            echo ✅ Готово"


            echo "⌛ Ожидание запуска контейнера 60..."
            sleep 60
            echo "⌛ Ожидание запуска контейнера 60..."
            sleep 60
            echo "⌛ Ожидание запуска контейнера 180..."
            sleep 180
            echo "⌛ Ожидание запуска контейнера 180..."
            sleep 180
            echo "⌛ Ожидание запуска контейнера 180..."
            sleep 180
            echo "⌛ Ожидание запуска контейнера 180..."
            sleep 180
            docker ps -a
            docker logs front-konstructor-prod || true


            echo "⌛ Ожидание запуска контейнера 180..."
            sleep 180
            echo "⌛ Ожидание запуска контейнера last sllep..."
            sleep 180
            docker ps -a
            docker logs front-konstructor-prod || true
