name: Deploy kpi-sales on push to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ CI запущен
        run: echo "🚀 GitHub Actions запущен"

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "🧩 Подключение к серверу"
            cd /var/www/html/next/kpi-sales
            git pull origin main
            tmux kill-session -t deploy-session || true
            tmux new -d -s deploy-session "docker-compose up -d --build && echo ✅ Готово"

            echo "⏳ 1 Жду, пока контейнер april-kpi-sales поднимется..."
            sleep 120


            docker ps -a
            docker logs april-kpi-sales || true


            echo "⏳ 2 Жду, пока контейнер april-kpi-sales поднимется..."
            sleep 300

            docker ps -a
            docker logs april-kpi-sales || true


            echo "⏳ 3 Жду, пока контейнер april-kpi-sales поднимется..."
            sleep 300

            docker ps -a
            docker logs april-kpi-sales || true


            echo "⏳4 Жду, пока контейнер april-kpi-sales поднимется..."
            sleep 300

            docker ps -a
            docker logs april-kpi-sales || true       



            echo "⏳5 Жду, пока контейнер april-kpi-sales поднимется..."
            sleep 300

            docker ps -a
            docker logs april-kpi-sales || true         
